create table if not exists public.player_development_trait_history (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  event_date date not null,
  trait_code text not null,
  old_value text,
  new_value text,
  reason text,
  source_label text not null default 'Court Boss development-v3',
  created_at timestamptz not null default now()
);
create index if not exists idx_player_dev_trait_history_player_date
  on public.player_development_trait_history(player_id,event_date desc,id desc);
alter table public.player_development_trait_history enable row level security;
revoke all on table public.player_development_trait_history from public, anon, authenticated;
grant select, insert on table public.player_development_trait_history to service_role;

create or replace function public.log_player_development_trait_changes()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_date date:=coalesce(new.last_review_date,(select career_date from public.career_state where id='demo'),current_date);
begin
  insert into public.player_development_trait_history(player_id,event_date,trait_code,old_value,new_value,reason)
  select new.player_id,v_date,x.code,x.oldv,x.newv,
    case x.code
      when 'professionalism' then 'Habitudes de travail et environnement professionnel'
      when 'coachability' then 'Réceptivité au coaching et stabilité du staff'
      when 'resilience' then 'Expérience des périodes difficiles, blessures et résultats'
      when 'discipline' then 'Routine de travail et comportement'
      when 'competitive_drive' then 'Ambition, motivation et phase de carrière'
      when 'development_rate' then 'Vitesse naturelle de progression et environnement'
      when 'confidence_volatility' then 'Stabilité émotionnelle acquise avec l’expérience'
      when 'potential_volatility' then 'Incertitude du plafond qui se réduit avec l’âge'
      when 'potential_momentum' then 'Tendance récente du potentiel'
      when 'decline_start_age' then 'Longévité physique et historique médical'
      when 'phase' then 'Transition de phase de carrière'
      else 'Évolution du profil de développement'
    end
  from (values
    ('professionalism',old.professionalism::text,new.professionalism::text),
    ('coachability',old.coachability::text,new.coachability::text),
    ('resilience',old.resilience::text,new.resilience::text),
    ('discipline',old.discipline::text,new.discipline::text),
    ('competitive_drive',old.competitive_drive::text,new.competitive_drive::text),
    ('development_rate',old.development_rate::text,new.development_rate::text),
    ('confidence_volatility',old.confidence_volatility::text,new.confidence_volatility::text),
    ('potential_volatility',old.potential_volatility::text,new.potential_volatility::text),
    ('potential_momentum',old.potential_momentum::text,new.potential_momentum::text),
    ('decline_start_age',old.decline_start_age::text,new.decline_start_age::text),
    ('phase',coalesce(old.development_context->>'phase',''),coalesce(new.development_context->>'phase',''))
  ) as x(code,oldv,newv)
  where x.oldv is distinct from x.newv;
  return new;
end;
$$;

revoke all on function public.log_player_development_trait_changes() from public, anon, authenticated;
grant execute on function public.log_player_development_trait_changes() to service_role;

drop trigger if exists trg_log_player_development_trait_changes on public.player_development_profiles;
create trigger trg_log_player_development_trait_changes
after update of professionalism,coachability,resilience,discipline,competitive_drive,
  development_rate,confidence_volatility,potential_volatility,potential_momentum,
  decline_start_age,development_context
on public.player_development_profiles
for each row execute function public.log_player_development_trait_changes();
