create table if not exists public.finance_transactions (
  id bigint generated by default as identity primary key,
  transaction_key text not null unique,
  game_date date not null,
  week integer,
  category text not null,
  amount numeric not null,
  currency text not null default 'EUR',
  source_type text,
  source_id bigint,
  description text not null,
  balance_after numeric,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.finance_transactions enable row level security;
create index if not exists ix_finance_transactions_date on public.finance_transactions(game_date desc,id desc);
create index if not exists ix_finance_transactions_category on public.finance_transactions(category,game_date desc);
insert into public.finance_transactions(
  transaction_key,game_date,week,category,amount,currency,source_type,description,balance_after,metadata
)
select
  'opening:'||coalesce(c.career_date::text,'2025-12-01'),
  coalesce(c.career_date,date '2025-12-01'),
  c.week,'opening',coalesce(c.budget,0),'EUR','career',
  'Solde d’ouverture du journal financier',coalesce(c.budget,0),
  jsonb_build_object('model','CB-FINANCE-LEDGER-v1')
from public.career_state c where c.id='demo'
on conflict (transaction_key) do nothing;
