-- Court Boss Hall of Fame V30
-- Dynamic retirement ceremonies, five-year eligibility, three-year ballot,
-- 75% election threshold, annual Newport classes, speeches and Legacy comparison.

create table if not exists public.court_boss_hof_profiles (
  player_id bigint primary key references public.players(id) on delete cascade,
  retired_date date not null,
  eligibility_year integer not null,
  status text not null default 'waiting' check(status in ('waiting','eligible','ballot','elected','inducted','expired','not_nominated')),
  first_nomination_year integer,
  ballots_count integer not null default 0,
  last_ballot_year integer,
  last_vote_pct numeric,
  peak_vote_pct numeric,
  hof_score bigint not null default 0,
  induction_year integer,
  induction_date date,
  class_number integer,
  legacy_rank_at_induction bigint,
  legacy_score_at_induction bigint,
  compared_to_player_id bigint references public.players(id) on delete set null,
  compared_to_player_name text,
  compared_to_rank bigint,
  retirement_ceremony_on date,
  retirement_speech text,
  induction_speech text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.court_boss_hof_ballots (
  id bigint generated by default as identity primary key,
  ballot_year integer not null,
  player_id bigint not null references public.players(id) on delete cascade,
  ballot_number integer not null check(ballot_number between 1 and 3),
  nomination_score bigint not null default 0,
  official_vote_pct numeric not null default 0,
  fan_rank integer,
  fan_bonus_pct numeric not null default 0,
  final_vote_pct numeric not null default 0,
  result text not null default 'nominated' check(result in ('nominated','elected','failed','final_ballot_failed')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(ballot_year,player_id)
);

create table if not exists public.court_boss_hof_classes (
  induction_year integer primary key,
  class_number integer not null,
  ballot_opened_on date,
  announced_on date,
  induction_date date not null,
  status text not null default 'voting' check(status in ('voting','elected','inducted','empty')),
  nominee_count integer not null default 0,
  elected_count integer not null default 0,
  inducted_count integer not null default 0,
  ceremony_title text,
  ceremony_location text not null default 'Newport, Rhode Island',
  summary text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.court_boss_retirement_ceremonies (
  player_id bigint primary key references public.players(id) on delete cascade,
  retirement_date date not null,
  ceremony_date date not null,
  player_name text not null,
  country text,
  legacy_rank bigint,
  legacy_score bigint,
  titles bigint not null default 0,
  grand_slams bigint not null default 0,
  masters bigint not null default 0,
  tour_finals bigint not null default 0,
  wins bigint not null default 0,
  weeks_no1 bigint not null default 0,
  eligibility_year integer not null,
  speech text not null,
  world_news_published boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.court_boss_hof_profiles enable row level security;
alter table public.court_boss_hof_ballots enable row level security;
alter table public.court_boss_hof_classes enable row level security;
alter table public.court_boss_retirement_ceremonies enable row level security;

revoke all on public.court_boss_hof_profiles from public,anon,authenticated;
revoke all on public.court_boss_hof_ballots from public,anon,authenticated;
revoke all on public.court_boss_hof_classes from public,anon,authenticated;
revoke all on public.court_boss_retirement_ceremonies from public,anon,authenticated;

grant select,insert,update,delete on public.court_boss_hof_profiles to service_role;
grant select,insert,update,delete on public.court_boss_hof_ballots to service_role;
grant select,insert,update,delete on public.court_boss_hof_classes to service_role;
grant select,insert,update,delete on public.court_boss_retirement_ceremonies to service_role;
grant usage,select on sequence public.court_boss_hof_ballots_id_seq to service_role;

create index if not exists idx_cb_hof_profiles_status
  on public.court_boss_hof_profiles(status,eligibility_year);
create index if not exists idx_cb_hof_ballots_year
  on public.court_boss_hof_ballots(ballot_year,result,final_vote_pct desc);
create index if not exists idx_cb_hof_profiles_induction
  on public.court_boss_hof_profiles(induction_year,class_number);

CREATE OR REPLACE FUNCTION public.court_boss_hall_of_fame_hub(p_date date DEFAULT '2025-12-01'::date)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_year int:=extract(year from p_date)::int;
  v_classes jsonb:='[]'::jsonb;
  v_ballot jsonb:='[]'::jsonb;
  v_inductees jsonb:='[]'::jsonb;
  v_waiting jsonb:='[]'::jsonb;
begin
  select coalesce(jsonb_agg(to_jsonb(c) order by c.induction_year desc),'[]'::jsonb)
  into v_classes
  from (
    select * from public.court_boss_hof_classes
    where induction_year<=v_year
    order by induction_year desc
    limit 12
  ) c;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'player_id',b.player_id,'player_name',p.name,'country',p.country,
      'ballot_year',b.ballot_year,'ballot_number',b.ballot_number,
      'official_vote_pct',b.official_vote_pct,'fan_rank',b.fan_rank,
      'fan_bonus_pct',b.fan_bonus_pct,'final_vote_pct',b.final_vote_pct,
      'result',b.result,'details',b.details
    ) order by b.final_vote_pct desc,b.nomination_score desc
  ),'[]'::jsonb)
  into v_ballot
  from public.court_boss_hof_ballots b
  join public.players p on p.id=b.player_id
  where b.ballot_year=v_year;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'player_id',hp.player_id,'player_name',p.name,'country',p.country,
      'induction_year',hp.induction_year,'induction_date',hp.induction_date,
      'class_number',hp.class_number,'legacy_rank',hp.legacy_rank_at_induction,
      'legacy_score',hp.legacy_score_at_induction,'vote_pct',hp.last_vote_pct,
      'comparison_player_name',hp.compared_to_player_name,'comparison_rank',hp.compared_to_rank,
      'speech',hp.induction_speech,'metadata',hp.metadata
    ) order by hp.induction_year desc,hp.legacy_score_at_induction desc
  ),'[]'::jsonb)
  into v_inductees
  from public.court_boss_hof_profiles hp
  join public.players p on p.id=hp.player_id
  where hp.status='inducted';

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'player_id',hp.player_id,'player_name',p.name,'country',p.country,
      'retired_date',hp.retired_date,'eligibility_year',hp.eligibility_year,
      'status',hp.status,'legacy_rank',l.all_time_rank,'legacy_score',l.legacy_score,
      'grand_slams',l.grand_slams,'titles',l.titles
    ) order by hp.eligibility_year,l.legacy_score desc
  ),'[]'::jsonb)
  into v_waiting
  from public.court_boss_hof_profiles hp
  join public.players p on p.id=hp.player_id
  left join public.court_boss_legacy_leaderboard(p_date) l on l.player_id=hp.player_id
  where hp.status in ('waiting','eligible','ballot','elected')
  limit 40;

  return jsonb_build_object(
    'date',p_date,'year',v_year,
    'current_class',(select to_jsonb(c) from public.court_boss_hof_classes c where c.induction_year=v_year),
    'ballot',v_ballot,'classes',v_classes,'inductees',v_inductees,'waiting',v_waiting,
    'counts',jsonb_build_object(
      'inducted',(select count(*) from public.court_boss_hof_profiles where status='inducted'),
      'waiting',(select count(*) from public.court_boss_hof_profiles where status='waiting'),
      'eligible',(select count(*) from public.court_boss_hof_profiles where status in ('eligible','ballot','elected')),
      'expired',(select count(*) from public.court_boss_hof_profiles where status='expired')
    ),
    'rules',jsonb_build_object(
      'wait_years',5,'max_ballot_years',3,'threshold_pct',75,
      'fan_bonus_top3',jsonb_build_array(3,2,1),
      'ceremony','dernier samedi d’août · Newport'
    ),
    'model','CB-HOF-HUB-v30'
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.court_boss_hof_induction_date(p_year integer)
 RETURNS date
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO ''
AS $function$
  select (
    make_date(p_year,8,31)
    - ((extract(dow from make_date(p_year,8,31))::int - 6 + 7) % 7)
  )::date
$function$;

CREATE OR REPLACE FUNCTION public.court_boss_hof_player_snapshot(p_player_id bigint, p_date date DEFAULT '2025-12-01'::date)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  hp public.court_boss_hof_profiles%rowtype;
  l record;
  above record;
  below record;
  goat record;
  v_ballots jsonb:='[]'::jsonb;
  v_retirement jsonb:='{}'::jsonb;
begin
  select * into hp from public.court_boss_hof_profiles where player_id=p_player_id;
  select * into l from public.court_boss_legacy_leaderboard(p_date) where player_id=p_player_id;
  select * into goat from public.court_boss_legacy_leaderboard(p_date) order by all_time_rank limit 1;

  if l.player_id is not null then
    select * into above
    from public.court_boss_legacy_leaderboard(p_date)
    where all_time_rank<l.all_time_rank
    order by all_time_rank desc limit 1;

    select * into below
    from public.court_boss_legacy_leaderboard(p_date)
    where all_time_rank>l.all_time_rank
    order by all_time_rank asc limit 1;
  end if;

  select coalesce(jsonb_agg(to_jsonb(b) order by b.ballot_year,b.ballot_number),'[]'::jsonb)
  into v_ballots
  from public.court_boss_hof_ballots b
  where b.player_id=p_player_id;

  select coalesce(to_jsonb(r),'{}'::jsonb)
  into v_retirement
  from public.court_boss_retirement_ceremonies r
  where r.player_id=p_player_id;

  return jsonb_build_object(
    'player_id',p_player_id,
    'status',coalesce(hp.status,case when (select career_status from public.players where id=p_player_id)='retired' then 'not_registered' else 'active' end),
    'retired_date',hp.retired_date,
    'eligibility_year',hp.eligibility_year,
    'first_nomination_year',hp.first_nomination_year,
    'ballots_count',coalesce(hp.ballots_count,0),
    'last_vote_pct',hp.last_vote_pct,
    'peak_vote_pct',hp.peak_vote_pct,
    'induction_year',hp.induction_year,
    'induction_date',hp.induction_date,
    'class_number',hp.class_number,
    'induction_speech',hp.induction_speech,
    'retirement_speech',hp.retirement_speech,
    'ballots',v_ballots,
    'retirement_ceremony',v_retirement,
    'legacy',case when l.player_id is null then null else jsonb_build_object(
      'rank',l.all_time_rank,'score',l.legacy_score,'titles',l.titles,'grand_slams',l.grand_slams,
      'masters',l.masters,'tour_finals',l.tour_finals,'wins',l.wins,'weeks_no1',l.weeks_no1
    ) end,
    'comparison',jsonb_build_object(
      'above',case when above.player_id is null then null else jsonb_build_object('player_id',above.player_id,'name',above.player_name,'rank',above.all_time_rank,'score',above.legacy_score) end,
      'below',case when below.player_id is null then null else jsonb_build_object('player_id',below.player_id,'name',below.player_name,'rank',below.all_time_rank,'score',below.legacy_score) end,
      'goat',case when goat.player_id is null then null else jsonb_build_object('player_id',goat.player_id,'name',goat.player_name,'rank',goat.all_time_rank,'score',goat.legacy_score) end,
      'induction_comparison',case when hp.compared_to_player_id is null then null else jsonb_build_object(
        'player_id',hp.compared_to_player_id,'name',hp.compared_to_player_name,'rank',hp.compared_to_rank
      ) end
    ),
    'rules',jsonb_build_object('wait_years',5,'max_ballot_years',3,'election_threshold_pct',75),
    'model','CB-HOF-PLAYER-v30'
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.court_boss_hof_process_year(p_date date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_date date:=coalesce(p_date,current_date);
  v_year integer:=extract(year from coalesce(p_date,current_date))::int;
  v_induction_date date;
  v_class_number integer;
  v_nominees integer:=0;
  v_elected integer:=0;
  v_inducted integer:=0;
  v_first_nominees integer:=0;
  v_names text;
  v_row record;
  v_cmp record;
  v_leg record;
  v_speech text;
begin
  if v_year<=2025 then
    return jsonb_build_object('ok',true,'date',v_date,'year',v_year,'historical_cutoff',true,'model','CB-HOF-v30');
  end if;

  v_induction_date:=public.court_boss_hof_induction_date(v_year);
  v_class_number:=v_year-1953;

  insert into public.court_boss_hof_classes(
    induction_year,class_number,ballot_opened_on,induction_date,status,
    ceremony_title,ceremony_location,metadata,updated_at
  ) values(
    v_year,v_class_number,make_date(v_year,1,15),v_induction_date,'voting',
    'Court Boss Hall of Fame · Classe '||v_year,
    'Newport, Rhode Island',
    jsonb_build_object(
      'eligibility_wait_years',5,'max_ballot_years',3,
      'election_threshold_pct',75,'historical_class_number',v_class_number
    ),now()
  )
  on conflict(induction_year) do update set
    class_number=excluded.class_number,
    induction_date=excluded.induction_date,
    updated_at=now();

  update public.court_boss_hof_profiles
  set status='eligible',updated_at=now()
  where status='waiting' and eligibility_year<=v_year;

  with eligible as (
    select
      hp.player_id,hp.ballots_count,
      lb.all_time_rank,lb.legacy_score,lb.titles,lb.grand_slams,lb.masters,lb.tour_finals,
      lb.wins,lb.losses,lb.weeks_no1,lb.player_of_year,
      pl.name,pl.country,
      (
        lb.legacy_score
        +lb.grand_slams*25000
        +lb.weeks_no1*60
        +lb.player_of_year*5000
      )::bigint nomination_score
    from public.court_boss_hof_profiles hp
    join public.players pl on pl.id=hp.player_id
    join public.court_boss_legacy_leaderboard(v_date) lb on lb.player_id=hp.player_id
    where hp.eligibility_year<=v_year
      and hp.status in ('eligible','ballot')
      and hp.ballots_count<3
      and not exists(
        select 1 from public.court_boss_hof_ballots hb
        where hb.ballot_year=v_year and hb.player_id=hp.player_id
      )
      and (
        lb.grand_slams>=1
        or lb.titles>=15
        or lb.masters>=5
        or lb.weeks_no1>=20
        or lb.wins>=400
        or lb.all_time_rank<=180
      )
  ),
  scored as (
    select e.*,
      greatest(35,least(99,
        round(
          48
          +least(28,e.grand_slams*4.0)
          +least(10,e.masters*.45)
          +least(6,e.tour_finals*1.5)
          +least(15,e.weeks_no1/20.0)
          +least(8,e.titles/10.0)
          +case
            when e.all_time_rank<=10 then 12
            when e.all_time_rank<=25 then 8
            when e.all_time_rank<=50 then 5
            when e.all_time_rank<=100 then 3
            else 0
          end
          +e.ballots_count*3
          +((abs(mod(hashtextextended('hof-vote|'||e.player_id::text||'|'||v_year::text,0),9)))-4)
        ,1)
      ))::numeric official_vote
    from eligible e
  )
  insert into public.court_boss_hof_ballots(
    ballot_year,player_id,ballot_number,nomination_score,official_vote_pct,
    fan_rank,fan_bonus_pct,final_vote_pct,result,details,updated_at
  )
  select
    v_year,s.player_id,s.ballots_count+1,s.nomination_score,s.official_vote,
    null,0,s.official_vote,'nominated',
    jsonb_build_object(
      'legacy_rank',s.all_time_rank,'legacy_score',s.legacy_score,
      'titles',s.titles,'grand_slams',s.grand_slams,'masters',s.masters,
      'tour_finals',s.tour_finals,'wins',s.wins,'weeks_no1',s.weeks_no1,
      'player_of_year',s.player_of_year
    ),now()
  from scored s
  on conflict(ballot_year,player_id) do nothing;

  get diagnostics v_nominees=row_count;

  with ranked as (
    select
      hb.id,
      row_number() over(order by hb.nomination_score desc,hb.player_id)::int fan_rank
    from public.court_boss_hof_ballots hb
    where hb.ballot_year=v_year
  )
  update public.court_boss_hof_ballots hb
  set
    fan_rank=rk.fan_rank,
    fan_bonus_pct=case rk.fan_rank when 1 then 3 when 2 then 2 when 3 then 1 else 0 end,
    final_vote_pct=least(100,hb.official_vote_pct+case rk.fan_rank when 1 then 3 when 2 then 2 when 3 then 1 else 0 end),
    updated_at=now()
  from ranked rk
  where rk.id=hb.id;

  update public.court_boss_hof_ballots hb
  set result=case
      when hb.final_vote_pct>=75 then 'elected'
      when hb.ballot_number>=3 then 'final_ballot_failed'
      else 'failed'
    end,
    updated_at=now()
  where hb.ballot_year=v_year;

  update public.court_boss_hof_profiles hp
  set
    first_nomination_year=coalesce(hp.first_nomination_year,hb.ballot_year),
    ballots_count=greatest(hp.ballots_count,hb.ballot_number),
    last_ballot_year=hb.ballot_year,
    last_vote_pct=hb.final_vote_pct,
    peak_vote_pct=greatest(coalesce(hp.peak_vote_pct,0),hb.final_vote_pct),
    hof_score=greatest(hp.hof_score,hb.nomination_score),
    status=case
      when hb.result='elected' then 'elected'
      when hb.result='final_ballot_failed' then 'expired'
      else 'ballot'
    end,
    updated_at=now()
  from public.court_boss_hof_ballots hb
  where hb.ballot_year=v_year and hb.player_id=hp.player_id;

  select count(*)::int into v_elected
  from public.court_boss_hof_ballots hb
  where hb.ballot_year=v_year and hb.result='elected';

  select count(*)::int into v_first_nominees
  from public.court_boss_hof_ballots hb
  where hb.ballot_year=v_year and hb.ballot_number=1;

  select string_agg(x.name,', ' order by x.nomination_score desc)
  into v_names
  from (
    select pl.name,hb.nomination_score
    from public.court_boss_hof_ballots hb
    join public.players pl on pl.id=hb.player_id
    where hb.ballot_year=v_year
    order by hb.nomination_score desc
    limit 6
  ) x;

  if exists(select 1 from public.court_boss_hof_ballots hb where hb.ballot_year=v_year) then
    perform public.court_boss_publish_world_story(
      'hof_ballot:'||v_year,
      greatest(v_date,make_date(v_year,1,15)),
      null,'hall_of_fame_ballot',
      'Hall of Fame '||v_year||' : le bulletin est ouvert'
        ||case when coalesce(v_names,'')<>'' then ' avec '||v_names else '' end
        ||'. Il faut 75 % pour rejoindre la classe annuelle.',
      jsonb_build_object(
        'year',v_year,'class_number',v_class_number,
        'nominee_count',(select count(*) from public.court_boss_hof_ballots hb where hb.ballot_year=v_year),
        'elected_count',v_elected,'threshold_pct',75
      )
    );
  end if;

  for v_row in
    select hb.*,pl.name,pl.country,
           (hb.details->>'legacy_rank')::bigint legacy_rank,
           coalesce((hb.details->>'grand_slams')::int,0) grand_slams
    from public.court_boss_hof_ballots hb
    join public.players pl on pl.id=hb.player_id
    where hb.ballot_year=v_year and hb.ballot_number=1
      and (
        coalesce((hb.details->>'legacy_rank')::bigint,999999)<=100
        or coalesce((hb.details->>'grand_slams')::int,0)>0
      )
  loop
    perform public.court_boss_publish_world_story(
      'hof_first_nomination:'||v_row.player_id,
      greatest(v_date,make_date(v_year,1,15)),
      v_row.player_id,'hall_of_fame_nomination',
      v_row.name||' apparaît pour la première fois sur le bulletin du Hall of Fame, '
        ||(v_year-extract(year from (select hp2.retired_date from public.court_boss_hof_profiles hp2 where hp2.player_id=v_row.player_id))::int)
        ||' ans après sa retraite.',
      jsonb_build_object(
        'year',v_year,'ballot_number',1,'official_vote_pct',v_row.official_vote_pct,
        'fan_bonus_pct',v_row.fan_bonus_pct,'final_vote_pct',v_row.final_vote_pct,
        'legacy_rank',v_row.legacy_rank,'grand_slams',v_row.grand_slams
      )
    );
  end loop;

  update public.court_boss_hof_classes hc
  set
    nominee_count=(select count(*) from public.court_boss_hof_ballots hb where hb.ballot_year=v_year),
    elected_count=v_elected,
    announced_on=coalesce(hc.announced_on,v_date),
    status=case
      when (select count(*) from public.court_boss_hof_ballots hb where hb.ballot_year=v_year)=0 then 'empty'
      when v_elected>0 then 'elected'
      else 'voting'
    end,
    summary=case
      when v_elected>0 then v_elected||' joueur'||case when v_elected>1 then 's' else '' end||' élu'||case when v_elected>1 then 's' else '' end||' pour la classe '||v_year||'.'
      else 'Aucun élu pour le moment dans la classe '||v_year||'.'
    end,
    updated_at=now()
  where hc.induction_year=v_year;

  if v_date>=v_induction_date then
    for v_row in
      select hb.*,pl.name,pl.country,hp.retired_date
      from public.court_boss_hof_ballots hb
      join public.players pl on pl.id=hb.player_id
      join public.court_boss_hof_profiles hp on hp.player_id=hb.player_id
      where hb.ballot_year=v_year
        and hb.result='elected'
        and hp.status='elected'
      order by hb.final_vote_pct desc,hb.nomination_score desc
    loop
      select * into v_leg
      from public.court_boss_legacy_leaderboard(v_induction_date) lb
      where lb.player_id=v_row.player_id;

      select * into v_cmp
      from public.court_boss_legacy_leaderboard(v_induction_date) lb
      where lb.player_id<>v_row.player_id
      order by abs(lb.all_time_rank-v_leg.all_time_rank),lb.all_time_rank
      limit 1;

      v_speech:='« Rejoindre cette classe après une carrière de '||coalesce(v_leg.titles,0)||' titres'
        ||case when coalesce(v_leg.grand_slams,0)>0 then ' et '||v_leg.grand_slams||' Majeur'||case when v_leg.grand_slams>1 then 's' else '' end else '' end
        ||' est un honneur immense. '
        ||case when v_cmp.player_name is not null
          then 'Être désormais cité aux côtés de '||v_cmp.player_name||' donne une autre dimension à tout ce parcours. '
          else '' end
        ||'Merci à tous ceux qui ont fait partie de cette histoire. »';

      update public.court_boss_hof_profiles hp
      set
        status='inducted',
        induction_year=v_year,
        induction_date=v_induction_date,
        class_number=v_class_number,
        legacy_rank_at_induction=v_leg.all_time_rank,
        legacy_score_at_induction=v_leg.legacy_score,
        compared_to_player_id=v_cmp.player_id,
        compared_to_player_name=v_cmp.player_name,
        compared_to_rank=v_cmp.all_time_rank,
        induction_speech=v_speech,
        metadata=hp.metadata||jsonb_build_object(
          'induction_vote_pct',v_row.final_vote_pct,
          'fan_rank',v_row.fan_rank,'fan_bonus_pct',v_row.fan_bonus_pct,
          'career_titles',v_leg.titles,'career_grand_slams',v_leg.grand_slams,
          'career_masters',v_leg.masters,'career_tour_finals',v_leg.tour_finals,
          'career_wins',v_leg.wins,'career_weeks_no1',v_leg.weeks_no1
        ),
        updated_at=now()
      where hp.player_id=v_row.player_id;

      insert into public.future_hall_of_fame_v15(
        id,name,country,birth_date,career_status,ranking,points,photo_url,
        titles,grand_slams,masters,tour_finals,wins,losses,win_pct,history_score,
        inducted_on,updated_at
      )
      select
        pl.id,pl.name,pl.country,pl.birth_date,pl.career_status,pl.ranking,pl.points,pl.photo_url,
        coalesce(v_leg.titles,0)::int,coalesce(v_leg.grand_slams,0)::int,coalesce(v_leg.masters,0)::int,
        coalesce(v_leg.tour_finals,0)::int,coalesce(v_leg.wins,0)::int,coalesce(v_leg.losses,0)::int,
        case when coalesce(v_leg.wins,0)+coalesce(v_leg.losses,0)>0
          then round(100.0*v_leg.wins/(v_leg.wins+v_leg.losses),1) else 0 end,
        least(2147483647,coalesce(v_leg.legacy_score,0))::int,
        v_induction_date,now()
      from public.players pl where pl.id=v_row.player_id
      on conflict(id) do update set
        name=excluded.name,country=excluded.country,birth_date=excluded.birth_date,
        career_status=excluded.career_status,ranking=excluded.ranking,points=excluded.points,
        photo_url=coalesce(excluded.photo_url,public.future_hall_of_fame_v15.photo_url),
        titles=excluded.titles,grand_slams=excluded.grand_slams,masters=excluded.masters,
        tour_finals=excluded.tour_finals,wins=excluded.wins,losses=excluded.losses,
        win_pct=excluded.win_pct,history_score=excluded.history_score,
        inducted_on=excluded.inducted_on,updated_at=now();

      perform public.court_boss_publish_world_story(
        'hof_induction:'||v_row.player_id,
        v_induction_date,v_row.player_id,'hall_of_fame_induction',
        v_row.name||' entre officiellement au Hall of Fame dans la classe '||v_year
          ||' (#'||v_class_number||' dans la chronologie Court Boss)'
          ||case when v_cmp.player_name is not null then ', avec un héritage désormais placé près de '||v_cmp.player_name else '' end
          ||'.',
        jsonb_build_object(
          'year',v_year,'class_number',v_class_number,'vote_pct',v_row.final_vote_pct,
          'legacy_rank',v_leg.all_time_rank,'legacy_score',v_leg.legacy_score,
          'comparison_player_id',v_cmp.player_id,'comparison_player_name',v_cmp.player_name,
          'comparison_rank',v_cmp.all_time_rank,'speech',v_speech
        )
      );

      v_inducted:=v_inducted+1;
    end loop;

    update public.court_boss_hof_classes hc
    set
      status=case when v_elected>0 then 'inducted' else 'empty' end,
      inducted_count=(select count(*) from public.court_boss_hof_profiles hp where hp.induction_year=v_year and hp.status='inducted'),
      summary=case
        when v_elected>0 then 'Classe '||v_year||' intronisée à Newport avec '||v_elected||' membre'||case when v_elected>1 then 's' else '' end||'.'
        else 'Aucune intronisation pour la classe '||v_year||'.'
      end,
      updated_at=now()
    where hc.induction_year=v_year;

    if v_elected>0 then
      select string_agg(pl.name,', ' order by hb.final_vote_pct desc,hb.nomination_score desc)
      into v_names
      from public.court_boss_hof_ballots hb
      join public.players pl on pl.id=hb.player_id
      where hb.ballot_year=v_year and hb.result='elected';

      perform public.court_boss_publish_world_story(
        'hof_class_ceremony:'||v_year,
        v_induction_date,null,'hall_of_fame_ceremony',
        'Newport célèbre la classe '||v_year||' du Hall of Fame : '||coalesce(v_names,'')||'.',
        jsonb_build_object(
          'year',v_year,'class_number',v_class_number,'induction_date',v_induction_date,
          'inductees',coalesce(v_names,''),'count',v_elected
        )
      );
    end if;
  end if;

  return jsonb_build_object(
    'ok',true,'date',v_date,'year',v_year,'class_number',v_class_number,
    'nominees',(select count(*) from public.court_boss_hof_ballots hb where hb.ballot_year=v_year),
    'new_nominees',v_nominees,'first_nominees',v_first_nominees,
    'elected',v_elected,'inducted',v_inducted,
    'induction_date',v_induction_date,'model','CB-HOF-v30'
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.court_boss_hof_register_retirement(p_player_id bigint, p_retired_date date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  p public.players%rowtype;
  l record;
  v_eligibility integer;
  v_speech text;
  v_publish boolean:=false;
begin
  select * into p from public.players where id=p_player_id;
  if p.id is null or p_retired_date is null then
    return jsonb_build_object('ok',false,'reason','player_or_date_missing');
  end if;

  select * into l
  from public.court_boss_legacy_leaderboard(p_retired_date)
  where player_id=p_player_id;

  v_eligibility:=extract(year from p_retired_date)::int+5;

  v_speech:='Après '||coalesce(l.titles,0)||' titres'
    ||case when coalesce(l.grand_slams,0)>0 then ', '||l.grand_slams||' Majeur'||case when l.grand_slams>1 then 's' else '' end else '' end
    ||' et '||coalesce(l.wins,0)||' victoires, '||p.name
    ||' referme sa carrière professionnelle. '
    ||case when coalesce(l.weeks_no1,0)>0 then 'Son passage au sommet pendant '||l.weeks_no1||' semaines restera une partie centrale de son héritage. '
      else 'Son héritage sera désormais jugé sur l’ensemble de son parcours. ' end
    ||'Première année d’éligibilité au Hall of Fame : '||v_eligibility||'.';

  insert into public.court_boss_hof_profiles(
    player_id,retired_date,eligibility_year,status,hof_score,
    retirement_ceremony_on,retirement_speech,metadata,updated_at
  ) values(
    p_player_id,p_retired_date,v_eligibility,'waiting',coalesce(l.legacy_score,0),
    p_retired_date,v_speech,
    jsonb_build_object(
      'legacy_rank_at_retirement',l.all_time_rank,
      'legacy_score_at_retirement',l.legacy_score,
      'titles',l.titles,'grand_slams',l.grand_slams,'masters',l.masters,
      'tour_finals',l.tour_finals,'wins',l.wins,'weeks_no1',l.weeks_no1
    ),now()
  )
  on conflict(player_id) do update set
    retired_date=excluded.retired_date,
    eligibility_year=excluded.eligibility_year,
    hof_score=greatest(public.court_boss_hof_profiles.hof_score,excluded.hof_score),
    retirement_ceremony_on=coalesce(public.court_boss_hof_profiles.retirement_ceremony_on,excluded.retirement_ceremony_on),
    retirement_speech=coalesce(public.court_boss_hof_profiles.retirement_speech,excluded.retirement_speech),
    metadata=public.court_boss_hof_profiles.metadata||excluded.metadata,
    updated_at=now();

  insert into public.court_boss_retirement_ceremonies(
    player_id,retirement_date,ceremony_date,player_name,country,
    legacy_rank,legacy_score,titles,grand_slams,masters,tour_finals,wins,weeks_no1,
    eligibility_year,speech,metadata,updated_at
  ) values(
    p_player_id,p_retired_date,p_retired_date,p.name,p.country,
    l.all_time_rank,l.legacy_score,coalesce(l.titles,0),coalesce(l.grand_slams,0),
    coalesce(l.masters,0),coalesce(l.tour_finals,0),coalesce(l.wins,0),coalesce(l.weeks_no1,0),
    v_eligibility,v_speech,
    jsonb_build_object('career_status','retired','retirement_reason',p.retirement_reason),
    now()
  )
  on conflict(player_id) do update set
    retirement_date=excluded.retirement_date,ceremony_date=excluded.ceremony_date,
    legacy_rank=excluded.legacy_rank,legacy_score=excluded.legacy_score,
    titles=excluded.titles,grand_slams=excluded.grand_slams,masters=excluded.masters,
    tour_finals=excluded.tour_finals,wins=excluded.wins,weeks_no1=excluded.weeks_no1,
    eligibility_year=excluded.eligibility_year,speech=excluded.speech,
    metadata=public.court_boss_retirement_ceremonies.metadata||excluded.metadata,updated_at=now();

  v_publish:=coalesce(l.all_time_rank,999999)<=200
    or coalesce(l.grand_slams,0)>0
    or coalesce(l.titles,0)>=10
    or coalesce(l.weeks_no1,0)>0;

  if v_publish then
    if public.court_boss_publish_world_story(
      'retirement:'||p_player_id,
      p_retired_date,p_player_id,'retirement',
      p.name||' met un terme à sa carrière après '||coalesce(l.titles,0)||' titres'
        ||case when coalesce(l.grand_slams,0)>0 then ', dont '||l.grand_slams||' en Grand Chelem' else '' end
        ||'. Il pourra être considéré pour le Hall of Fame à partir de '||v_eligibility||'.',
      jsonb_build_object(
        'legacy_rank',l.all_time_rank,'legacy_score',l.legacy_score,
        'titles',l.titles,'grand_slams',l.grand_slams,'wins',l.wins,
        'eligibility_year',v_eligibility,'speech',v_speech
      )
    ) then
      update public.court_boss_retirement_ceremonies
      set world_news_published=true,updated_at=now()
      where player_id=p_player_id;
    end if;
  end if;

  return jsonb_build_object(
    'ok',true,'player_id',p_player_id,'retired_date',p_retired_date,
    'eligibility_year',v_eligibility,'published',v_publish,'model','CB-HOF-RETIREMENT-v1'
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.court_boss_hof_retirement_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if lower(coalesce(new.career_status,''))='retired'
     and (
       lower(coalesce(old.career_status,''))<>'retired'
       or old.retired_date is distinct from new.retired_date
     )
     and new.retired_date is not null
  then
    perform public.court_boss_hof_register_retirement(new.id,new.retired_date);
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_hall_of_fame_dynamic_v15(p_date date DEFAULT CURRENT_DATE)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_date date:=coalesce(p_date,current_date);
  v_registered int:=0;
  v_process jsonb;
  r record;
begin
  if v_date<=date '2025-12-01' then
    return jsonb_build_object('ok',true,'date',v_date,'historical_cutoff',true,'model','CB-HOF-v30');
  end if;

  for r in
    select p.id,p.retired_date
    from public.players p
    where lower(coalesce(p.career_status,''))='retired'
      and p.retired_date is not null
      and p.retired_date>=date '2026-01-01'
      and not exists(select 1 from public.court_boss_hof_profiles hp where hp.player_id=p.id)
  loop
    perform public.court_boss_hof_register_retirement(r.id,r.retired_date);
    v_registered:=v_registered+1;
  end loop;

  v_process:=public.court_boss_hof_process_year(v_date);

  return jsonb_build_object(
    'ok',true,'date',v_date,'registered_retirees',v_registered,
    'cycle',v_process,
    'historical_total',(select count(*) from public.history_player_scores h where h.grand_slams>=1 or h.titles>=25 or h.wins>=500),
    'future_inducted',(select count(*) from public.court_boss_hof_profiles where status='inducted'),
    'waiting',(select count(*) from public.court_boss_hof_profiles where status='waiting'),
    'on_ballot',(select count(*) from public.court_boss_hof_profiles where status in ('eligible','ballot','elected')),
    'model','CB-HALL-OF-FAME-v30'
  );
end;
$function$;

drop trigger if exists trg_cb_hof_retirement on public.players;
create trigger trg_cb_hof_retirement
after update of career_status,retired_date on public.players
for each row execute function public.court_boss_hof_retirement_trigger();

revoke all on function public.court_boss_hof_induction_date(integer) from public,anon,authenticated;
grant execute on function public.court_boss_hof_induction_date(integer) to service_role;
revoke all on function public.court_boss_hof_register_retirement(bigint,date) from public,anon,authenticated;
grant execute on function public.court_boss_hof_register_retirement(bigint,date) to service_role;
revoke all on function public.court_boss_hof_retirement_trigger() from public,anon,authenticated;
revoke all on function public.court_boss_hof_process_year(date) from public,anon,authenticated;
grant execute on function public.court_boss_hof_process_year(date) to service_role;
revoke all on function public.court_boss_hof_player_snapshot(bigint,date) from public,anon,authenticated;
grant execute on function public.court_boss_hof_player_snapshot(bigint,date) to service_role;
revoke all on function public.court_boss_hall_of_fame_hub(date) from public,anon,authenticated;
grant execute on function public.court_boss_hall_of_fame_hub(date) to service_role;
revoke all on function public.refresh_hall_of_fame_dynamic_v15(date) from public,anon,authenticated;
grant execute on function public.refresh_hall_of_fame_dynamic_v15(date) to service_role;
