-- Court Boss Career OS v1
-- DB migration version: 20260930222059

create table if not exists public.game_save_slots (
  id bigint generated by default as identity primary key,
  browser_key text not null,
  slot_no integer not null check (slot_no between 0 and 9),
  slot_type text not null default 'manual' check (slot_type in ('manual','autosave','quick')),
  slot_name text not null default 'Sauvegarde',
  local_payload jsonb not null default '{}'::jsonb,
  managed_snapshot jsonb not null default '{}'::jsonb,
  career_date date, week integer, player_name text, managed_player_id bigint,
  snapshot_scope text not null default 'managed_world_v1',
  game_version text not null default '2026.10-career-os-v1',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(browser_key,slot_no)
);
create index if not exists ix_game_save_slots_browser_updated on public.game_save_slots(browser_key,updated_at desc);
alter table public.game_save_slots enable row level security;

create table if not exists public.career_event_log (
  id bigint generated by default as identity primary key,
  event_date date not null, week integer, system text not null, event_type text not null,
  entity_type text, entity_id bigint, summary text not null,
  payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists ix_career_event_log_date on public.career_event_log(event_date desc,id desc);
alter table public.career_event_log enable row level security;

create table if not exists public.academy_intake_history (
  id bigint generated by default as identity primary key,
  academy_id text not null default 'demo',
  youth_id bigint references public.academy_youth(id) on delete set null,
  intake_year integer not null, generated_on date not null, country text, initial_ca integer,
  potential_floor integer, potential_ceiling integer, signed boolean not null default false,
  destination text, created_at timestamptz not null default now(),
  unique(academy_id,intake_year,youth_id)
);
alter table public.academy_intake_history enable row level security;

create table if not exists public.media_events (
  id bigint generated by default as identity primary key,
  event_date date not null, kind text not null, headline text not null, body text not null,
  tone text not null default 'neutral', priority text not null default 'normal',
  action_route text, related_player_id bigint, related_tournament_id bigint,
  created_at timestamptz not null default now()
);
create index if not exists ix_media_events_date on public.media_events(event_date desc,id desc);
alter table public.media_events enable row level security;

alter table public.inbox_items
  add column if not exists game_date date,
  add column if not exists priority text not null default 'normal',
  add column if not exists action_type text,
  add column if not exists action_label text,
  add column if not exists action_payload jsonb not null default '{}'::jsonb,
  add column if not exists secondary_action_type text,
  add column if not exists secondary_action_label text,
  add column if not exists secondary_action_payload jsonb not null default '{}'::jsonb,
  add column if not exists decision_status text not null default 'pending',
  add column if not exists related_entity_type text,
  add column if not exists related_entity_id bigint,
  add column if not exists expires_at date;

alter table public.academies
  add column if not exists academy_level integer not null default 1,
  add column if not exists youth_capacity integer not null default 8,
  add column if not exists scholarship_budget numeric not null default 10000,
  add column if not exists junior_reputation integer not null default 40,
  add column if not exists recruitment_reach integer not null default 2,
  add column if not exists development_intensity integer not null default 2,
  add column if not exists ncaa_pathway integer not null default 50,
  add column if not exists pro_pathway integer not null default 50,
  add column if not exists intake_month integer not null default 3,
  add column if not exists head_of_youth_profile_id bigint,
  add column if not exists academy_style text not null default 'Équilibré';

alter table public.academy_youth
  add column if not exists birth_date date,
  add column if not exists handedness text,
  add column if not exists backhand text,
  add column if not exists personality text,
  add column if not exists potential_floor integer,
  add column if not exists potential_ceiling integer,
  add column if not exists scouting_confidence integer not null default 45,
  add column if not exists region text,
  add column if not exists pathway_preference text not null default 'undecided',
  add column if not exists ncaa_interest integer not null default 50,
  add column if not exists pro_interest integer not null default 50,
  add column if not exists morale integer not null default 70,
  add column if not exists training_load integer not null default 50,
  add column if not exists injury_status text not null default 'Fit',
  add column if not exists signed_on date,
  add column if not exists last_review_date date,
  add column if not exists intake_year integer,
  add column if not exists source_label text not null default 'Court Boss Academy';

update public.academies
set academy_level=greatest(1,coalesce(academy_level,1)),
    youth_capacity=greatest(8,coalesce(youth_capacity,8)),
    scholarship_budget=greatest(10000,coalesce(scholarship_budget,10000)),
    junior_reputation=greatest(coalesce(reputation,40)-5,coalesce(junior_reputation,40)),
    recruitment_reach=greatest(coalesce(scouting_network,2),coalesce(recruitment_reach,2)),
    development_intensity=greatest(2,coalesce(development_intensity,2)),
    ncaa_pathway=coalesce(ncaa_pathway,50), pro_pathway=coalesce(pro_pathway,50),
    intake_month=coalesce(intake_month,3)
where id='demo';

update public.academy_youth
set potential_floor=coalesce(potential_floor,greatest(current_ability+6,potential-8)),
    potential_ceiling=coalesce(potential_ceiling,least(99,potential+5)),
    scouting_confidence=coalesce(scouting_confidence,55),
    personality=coalesce(personality,case (id % 5) when 0 then 'Très professionnel' when 1 then 'Ambitieux' when 2 then 'Travailleur' when 3 then 'Créatif' else 'Compétiteur' end),
    handedness=coalesce(handedness,case when id % 6=0 then 'Gaucher' else 'Droitier' end),
    backhand=coalesce(backhand,case when id % 7=0 then '1 main' else '2 mains' end),
    intake_year=coalesce(intake_year,2025),
    last_review_date=coalesce(last_review_date,date '2025-12-01');

CREATE OR REPLACE FUNCTION public.academy_refresh_intake(p_date date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  a public.academies%rowtype;
  v_year int:=extract(year from p_date)::int;
  v_month int:=extract(month from p_date)::int;
  v_existing int:=0;
  v_active int:=0;
  v_slots int:=0;
  v_count int:=0;
  v_i int;
  v_seed int;
  v_country text;
  v_name text;
  v_age int;
  v_ca int;
  v_mid_pa int;
  v_floor int;
  v_ceiling int;
  v_cost numeric;
  v_youth_id bigint;
  v_styles text[]:=array['Contreur agressif','All-court','Serveur-attaquant','Fond de court offensif','Défenseur / contre','Terre battue / lift','Prise de balle précoce'];
  v_personalities text[]:=array['Très professionnel','Ambitieux','Travailleur','Créatif','Compétiteur','Calme','Volontaire','Instinctif'];
  v_countries text[]:=array['FRA','ESP','ITA','CZE','USA','GBR','GER','ARG','BRA','SRB','CRO','BEL','NED','SWE','NOR','AUS','CAN','JPN'];
begin
  select * into a from public.academies where id='demo';
  if a.id is null then
    return jsonb_build_object('ok',false,'reason','academy_missing');
  end if;

  if v_month<>coalesce(a.intake_month,3) then
    return jsonb_build_object('ok',true,'created',0,'reason','outside_intake_month','month',v_month,'intake_month',a.intake_month);
  end if;

  select count(*) into v_existing
  from public.academy_intake_history
  where academy_id='demo' and intake_year=v_year;

  if v_existing>0 then
    return jsonb_build_object('ok',true,'created',0,'reason','already_generated','year',v_year);
  end if;

  select count(*) into v_active
  from public.academy_youth
  where status in ('prospect','signed','academy');

  v_slots:=greatest(0,coalesce(a.youth_capacity,8)-v_active);
  v_count:=least(v_slots,greatest(2,least(6,1+coalesce(a.recruitment_reach,2)+coalesce(a.academy_level,1)/2)));

  for v_i in 1..v_count loop
    v_seed:=v_year*1000+v_i*97+coalesce(a.recruitment_reach,2)*31+coalesce(a.junior_reputation,40);
    v_country:=case
      when v_i=1 then coalesce(a.country,'FRA')
      when v_i=2 and coalesce(a.recruitment_reach,2)>=2 then 'ESP'
      else v_countries[1+(abs(hashtext('academy-country|'||v_seed::text)) % array_length(v_countries,1))]
    end;
    v_name:=public.cb_generated_player_name(v_country,v_seed);
    if exists(select 1 from public.academy_youth where lower(name)=lower(v_name)) then
      v_name:=public.cb_generated_player_name(v_country,v_seed+701);
    end if;
    v_age:=13+(abs(hashtext('academy-age|'||v_seed::text)) % 5);
    v_ca:=greatest(27,least(58,
      30
      +coalesce(a.academy_level,1)*2
      +coalesce(a.development_intensity,2)
      +(abs(hashtext('academy-ca|'||v_seed::text)) % 13)
    ));
    v_mid_pa:=greatest(v_ca+10,least(96,
      61
      +coalesce(a.junior_reputation,40)/4
      +coalesce(a.scouting_network,2)
      +(abs(hashtext('academy-pa|'||v_seed::text)) % 19)
    ));
    v_floor:=greatest(v_ca+5,v_mid_pa-(10-greatest(1,coalesce(a.scouting_network,2))));
    v_ceiling:=least(99,v_mid_pa+greatest(3,9-coalesce(a.scouting_network,2)));
    v_cost:=greatest(500,round(450+v_ca*10+v_mid_pa*9+v_age*18));

    insert into public.academy_youth(
      name,country,age,potential,current_ability,style,scholarship_cost,status,
      birth_date,handedness,backhand,personality,potential_floor,potential_ceiling,
      scouting_confidence,region,pathway_preference,ncaa_interest,pro_interest,
      morale,training_load,injury_status,last_review_date,intake_year,source_label
    )
    values(
      v_name,v_country,v_age,v_mid_pa,v_ca,
      v_styles[1+(abs(hashtext('academy-style|'||v_seed::text)) % array_length(v_styles,1))],
      v_cost,'prospect',
      make_date(v_year-v_age,1+(abs(hashtext('academy-month|'||v_seed::text))%12),1+(abs(hashtext('academy-day|'||v_seed::text))%27)),
      case when abs(hashtext('academy-hand|'||v_seed::text))%8=0 then 'Gaucher' else 'Droitier' end,
      case when abs(hashtext('academy-bh|'||v_seed::text))%9=0 then '1 main' else '2 mains' end,
      v_personalities[1+(abs(hashtext('academy-personality|'||v_seed::text)) % array_length(v_personalities,1))],
      v_floor,v_ceiling,
      least(92,42+coalesce(a.scouting_network,2)*6+coalesce(a.recruitment_reach,2)*3),
      case when v_country=coalesce(a.country,'FRA') then 'National' else 'International' end,
      case
        when v_country='USA' then 'ncaa'
        when v_age>=17 and abs(hashtext('academy-path|'||v_seed::text))%100 < coalesce(a.ncaa_pathway,50) then 'ncaa'
        when v_age>=17 then 'pro'
        else 'undecided'
      end,
      greatest(20,least(95,35+coalesce(a.ncaa_pathway,50)/2+(abs(hashtext('academy-ncaa|'||v_seed::text))%31))),
      greatest(20,least(95,35+coalesce(a.pro_pathway,50)/2+(abs(hashtext('academy-pro|'||v_seed::text))%31))),
      64+(abs(hashtext('academy-morale|'||v_seed::text))%25),
      42+(abs(hashtext('academy-load|'||v_seed::text))%22),
      'Fit',p_date,v_year,'Court Boss Academy Intake v1'
    )
    returning id into v_youth_id;

    insert into public.academy_intake_history(
      academy_id,youth_id,intake_year,generated_on,country,initial_ca,potential_floor,potential_ceiling
    ) values('demo',v_youth_id,v_year,p_date,v_country,v_ca,v_floor,v_ceiling);

    v_count:=v_count;
  end loop;

  if v_count>0 then
    insert into public.inbox_items(
      kind,title,body,action_route,is_read,game_date,priority,action_type,action_label,action_payload,
      related_entity_type,decision_status
    ) values(
      'academy','Nouvelle promotion de l’académie',
      v_count||' nouveau(x) jeune(s) ont été détectés pour la promotion '||v_year||'. Les évaluations de potentiel sont volontairement imprécises.',
      'academy',false,p_date,'high','open_route','Voir les jeunes',jsonb_build_object('route','academy'),
      'academy_intake','info'
    );

    insert into public.career_event_log(event_date,system,event_type,entity_type,summary,payload)
    values(p_date,'academy','youth_intake','academy','Nouvelle promotion annuelle de jeunes',
      jsonb_build_object('year',v_year,'created',v_count));
  end if;

  return jsonb_build_object('ok',true,'created',v_count,'year',v_year,'capacity',a.youth_capacity,'active_before',v_active);
end;
$function$;

CREATE OR REPLACE FUNCTION public.academy_weekly_storylines(p_date date, p_week integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  a public.academies%rowtype;
  r record;
  v_reviewed int:=0;
  v_decisions int:=0;
  v_facility numeric:=1;
begin
  select * into a from public.academies where id='demo';
  select coalesce(avg(level),1) into v_facility from public.facilities;

  update public.academy_youth y
  set
    age=greatest(13,extract(year from age(p_date,coalesce(y.birth_date,make_date(extract(year from p_date)::int-y.age,7,1))))::int),
    morale=greatest(35,least(100,y.morale + case when y.training_load between 42 and 65 then 1 when y.training_load>80 then -2 else 0 end)),
    current_ability=case
      when p_week%4=0 and y.status in ('prospect','signed','academy')
        then least(coalesce(y.potential_ceiling,y.potential,99),y.current_ability+
          case when abs(hashtext('academy-dev|'||y.id||'|'||p_date::text))%100 <
            least(75,12+coalesce(a.development_intensity,2)*7+round(v_facility*3)::int)
          then 1 else 0 end)
      else y.current_ability
    end,
    scouting_confidence=least(100,y.scouting_confidence+case when p_week%4=0 then 2+coalesce(a.scouting_network,2) else 0 end),
    potential_floor=case when p_week%4=0 then least(coalesce(y.potential_ceiling,y.potential,99),coalesce(y.potential_floor,y.potential-8)+case when y.scouting_confidence<85 then 1 else 0 end) else y.potential_floor end,
    potential_ceiling=case when p_week%4=0 then greatest(coalesce(y.potential_floor,y.potential-8),coalesce(y.potential_ceiling,y.potential+5)-case when y.scouting_confidence<85 then 1 else 0 end) else y.potential_ceiling end,
    last_review_date=case when p_week%4=0 then p_date else y.last_review_date end
  where y.status in ('prospect','signed','academy');

  get diagnostics v_reviewed=row_count;

  for r in
    select *
    from public.academy_youth y
    where y.status='prospect'
      and y.age>=18
      and not exists(
        select 1 from public.inbox_items i
        where i.related_entity_type='academy_youth'
          and i.related_entity_id=y.id
          and i.action_type='academy_pathway'
          and i.decision_status='pending'
      )
  loop
    insert into public.inbox_items(
      kind,title,body,action_route,is_read,game_date,priority,
      action_type,action_label,action_payload,
      secondary_action_type,secondary_action_label,secondary_action_payload,
      related_entity_type,related_entity_id,decision_status,expires_at
    ) values(
      'academy','Décision de carrière · '||r.name,
      r.name||' a maintenant '||r.age||' ans. Choisis sa prochaine étape : circuit professionnel ou voie NCAA.',
      'academy',false,p_date,'high',
      'academy_pathway','Passer pro',jsonb_build_object('youth_id',r.id,'decision','pro'),
      'academy_pathway','NCAA',jsonb_build_object('youth_id',r.id,'decision','ncaa'),
      'academy_youth',r.id,'pending',p_date+21
    );
    v_decisions:=v_decisions+1;
  end loop;

  return jsonb_build_object('ok',true,'reviewed',v_reviewed,'pathway_decisions',v_decisions);
end;
$function$;

CREATE OR REPLACE FUNCTION public.career_generate_media_event(p_date date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  c public.career_state%rowtype;
  v_kind text;
  v_headline text;
  v_body text;
  v_tone text:='neutral';
begin
  select * into c from public.career_state where id='demo';

  if exists(
    select 1 from public.media_events
    where date_trunc('month',event_date)=date_trunc('month',p_date)
      and related_player_id=c.managed_player_id
  ) then
    return jsonb_build_object('ok',true,'created',false,'reason','monthly_story_exists');
  end if;

  if coalesce(c.singles_rank,999999)<=20 then
    v_kind:='spotlight'; v_tone:='positive';
    v_headline:=c.player_name||' s’installe parmi l’élite';
    v_body:='Le classement et les résultats récents placent '||c.player_name||' au centre de l’attention médiatique. La pression autour des grands rendez-vous augmente.';
  elsif coalesce(c.form,70)>=82 then
    v_kind:='form'; v_tone:='positive';
    v_headline:='Une dynamique qui attire les regards';
    v_body:=c.player_name||' traverse une période de très bonne forme. Les médias commencent à parler d’une possible montée en puissance.';
  elsif coalesce(c.fatigue,0)>=72 then
    v_kind:='workload'; v_tone:='concern';
    v_headline:='La charge de travail questionne';
    v_body:='La fatigue élevée de '||c.player_name||' alimente les questions sur la programmation et la récupération.';
  else
    v_kind:='career'; v_tone:='neutral';
    v_headline:='Le projet '||c.player_name||' continue de se construire';
    v_body:='Le staff poursuit son travail sur la progression, le calendrier et les objectifs de la saison.';
  end if;

  insert into public.media_events(event_date,kind,headline,body,tone,priority,action_route,related_player_id)
  values(p_date,v_kind,v_headline,v_body,v_tone,'normal','myplayer',c.managed_player_id);

  insert into public.inbox_items(
    kind,title,body,action_route,is_read,game_date,priority,action_type,action_label,action_payload,
    related_entity_type,related_entity_id,decision_status
  ) values(
    'media',v_headline,v_body,'myplayer',false,p_date,'normal',
    'open_route','Voir mon joueur',jsonb_build_object('route','myplayer'),
    'player',c.managed_player_id,'info'
  );

  return jsonb_build_object('ok',true,'created',true,'kind',v_kind,'headline',v_headline);
end;
$function$;

CREATE OR REPLACE FUNCTION public.career_publish_weekly_digest(p_date date, p_week integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  c public.career_state%rowtype;
  v_unread int:=0;
  v_injuries int:=0;
  v_scouts int:=0;
  v_expiring int:=0;
  v_body text;
begin
  select * into c from public.career_state where id='demo';
  select count(*) into v_unread from public.inbox_items where not is_read;
  select count(*) into v_injuries from public.injuries where status='Active';
  select count(*) into v_scouts from public.scouting_assignments where status='completed' and coalesce(last_update,p_date)>=p_date-7;
  select count(*) into v_expiring from public.contracts where status='active' and end_date between p_date and p_date+35;

  if exists(select 1 from public.inbox_items where kind='weekly_digest' and game_date=p_date) then
    return jsonb_build_object('ok',true,'created',false,'reason','already_exists');
  end if;

  v_body:='Classement simple #'||coalesce(c.singles_rank,0)||' · double #'||coalesce(c.doubles_rank,0)||
    ' · forme '||coalesce(c.form,0)||'% · fitness '||coalesce(c.fitness,0)||'% · fatigue '||coalesce(c.fatigue,0)||'%.'||
    case when v_injuries>0 then ' '||v_injuries||' blessure(s) active(s) dans le monde.' else '' end||
    case when v_scouts>0 then ' '||v_scouts||' mission(s) scouting terminée(s).' else '' end||
    case when v_expiring>0 then ' '||v_expiring||' contrat(s) arrivent à échéance sous 5 semaines.' else '' end;

  insert into public.inbox_items(
    kind,title,body,action_route,is_read,game_date,priority,action_type,action_label,action_payload,decision_status
  ) values(
    'weekly_digest','Rapport manager · semaine '||p_week,v_body,'home',false,p_date,
    case when v_expiring>0 or coalesce(c.fatigue,0)>=70 then 'high' else 'normal' end,
    'open_route','Ouvrir le centre manager',jsonb_build_object('route','home'),'info'
  );

  insert into public.career_event_log(event_date,week,system,event_type,summary,payload)
  values(p_date,p_week,'career','weekly_digest','Rapport manager hebdomadaire',
    jsonb_build_object('rank',c.singles_rank,'doubles_rank',c.doubles_rank,'fitness',c.fitness,'fatigue',c.fatigue,'expiring_contracts',v_expiring));

  return jsonb_build_object('ok',true,'created',true,'unread_before',v_unread,'expiring_contracts',v_expiring);
end;
$function$;

CREATE OR REPLACE FUNCTION public.career_system_health(p_date date)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object(
    'ok',true,
    'date',p_date,
    'career_exists',exists(select 1 from public.career_state where id='demo'),
    'managed_player_exists',exists(
      select 1 from public.players p join public.career_state c on c.managed_player_id=p.id where c.id='demo'
    ),
    'academy_exists',exists(select 1 from public.academies where id='demo'),
    'academy_active_players',(select count(*) from public.academy_roster where status='active'),
    'academy_prospects',(select count(*) from public.academy_youth where status='prospect'),
    'unread_inbox',(select count(*) from public.inbox_items where not is_read),
    'active_injuries',(select count(*) from public.injuries where status='Active'),
    'active_scouting',(select count(*) from public.scouting_assignments where status='active'),
    'available_sponsors',(select count(*) from public.sponsor_offers where status='available'),
    'active_staff',(select count(*) from public.staff),
    'active_contracts',(select count(*) from public.contracts where status='active'),
    'relationships',(select count(*) from public.player_relationships where active),
    'season_plans',(select count(*) from public.player_season_plans where season=extract(year from p_date)::int),
    'model','CB-CAREER-OS-v1'
  )
$function$;
