-- Court Boss · Next Gen ATP Finals selection v2
-- Game rule: Top 8 U21 by ATP ranking. Elite players may decline, max 2 AI refusals.

create table if not exists public.nextgen_finals_invitations (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  field_slot integer not null check (field_slot between 1 and 8),
  atp_rank integer not null,
  selection_order integer not null,
  is_managed boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending','accepted','declined','ai_declined','expired','unavailable')),
  invited_on date not null,
  respond_by date,
  responded_on date,
  refusal_probability numeric,
  refusal_reason text,
  decision_meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tournament_id,player_id)
);

create index if not exists nextgen_finals_inv_event_status_idx
  on public.nextgen_finals_invitations(tournament_id,status,field_slot);

alter table public.nextgen_finals_invitations enable row level security;

create or replace function public.nextgen_is_managed_player(p_player_id bigint)
returns boolean
language sql
stable
set search_path='public'
as $function$
  select exists(
    select 1 from public.career_state c
    where c.id='demo' and c.managed_player_id=p_player_id
  ) or exists(
    select 1 from public.academy_roster ar
    where ar.player_id=p_player_id and ar.status='active'
  );
$function$;

create or replace function public.nextgen_finals_ai_refusal(
  p_tournament_id bigint,
  p_player_id bigint,
  p_atp_rank integer
)
returns jsonb
language plpgsql
stable
set search_path='public'
as $function$
declare
  p public.players%rowtype;
  prob numeric:=0.01;
  roll numeric;
  reason text:='available';
begin
  select * into p from public.players where id=p_player_id;
  if p.id is null then
    return jsonb_build_object('accept',false,'probability',1,'reason','missing_player');
  end if;

  if coalesce(p.injury_status,'Fit')<>'Fit' or coalesce(p.fitness,90)<45 then
    return jsonb_build_object('accept',false,'probability',1,'reason','physical_unavailable');
  end if;

  prob:=case
    when p_atp_rank<=3 then .30
    when p_atp_rank<=5 then .25
    when p_atp_rank<=10 then .18
    when p_atp_rank<=20 then .10
    when p_atp_rank<=50 then .035
    else .01
  end;

  if coalesce(p.race_ranking,999999)<=8 then prob:=prob+.05; end if;
  if coalesce(p.fatigue,20)>=70 then prob:=prob+.04; end if;
  if coalesce(p.form,70)>=85 then prob:=prob-.025; end if;
  prob:=greatest(.005,least(.35,prob));

  roll:=mod(abs(hashtext('nextgen-finals-refusal|'||p_tournament_id||'|'||p_player_id))::bigint,10000)/10000.0;

  if roll<prob then
    reason:=case
      when coalesce(p.race_ranking,999999)<=8 then 'senior_finals_priority'
      when coalesce(p.fatigue,20)>=70 then 'schedule_and_fatigue'
      when p_atp_rank<=10 then 'elite_schedule_choice'
      else 'schedule_choice'
    end;
  end if;

  return jsonb_build_object(
    'accept',roll>=prob,
    'probability',round(prob,4),
    'roll',round(roll,4),
    'reason',reason,
    'atp_rank',p_atp_rank
  );
end;
$function$;

create or replace function public.nextgen_finals_candidate_pool(p_tournament_id bigint)
returns table(
  player_id bigint,
  player_name text,
  country text,
  atp_rank integer,
  nextgen_rank integer,
  is_managed boolean,
  injury_status text,
  fitness integer,
  fatigue integer,
  race_ranking integer
)
language sql
stable
set search_path='public'
as $function$
  with event as (
    select id,start_date,extract(year from start_date)::int season
    from public.tournaments
    where id=p_tournament_id
      and circuit='ATP'
      and category='Next Gen Finals'
    limit 1
  )
  select
    p.id,
    p.name,
    p.country,
    coalesce(
      public.player_rank_at_date(p.id,e.start_date-1),
      p.game_world_rank,
      case when p.ranking_current then p.ranking end,
      p.ranking,
      999999
    )::int as atp_rank,
    p.nextgen_ranking::int,
    public.nextgen_is_managed_player(p.id),
    coalesce(p.injury_status,'Fit'),
    coalesce(p.fitness,90)::int,
    coalesce(p.fatigue,20)::int,
    coalesce(p.race_ranking,999999)::int
  from public.players p
  cross join event e
  where public.nextgen_player_eligible(p.id,e.season)
    and p.career_status='active'
    and coalesce(p.data_source,'') not ilike 'hidden duplicate merged into %'
  order by atp_rank,p.id;
$function$;

create or replace function public.nextgen_fill_finals_slot(
  p_tournament_id bigint,
  p_field_slot integer,
  p_invited_on date,
  p_allow_managed_pending boolean default true
)
returns jsonb
language plpgsql
set search_path='public'
as $function$
declare
  rec record;
  ai jsonb;
  v_refusals int:=0;
  v_inv_id bigint;
  v_respond_by date;
begin
  if p_field_slot not between 1 and 8 then
    return jsonb_build_object('ok',false,'reason','invalid_slot');
  end if;

  if exists(
    select 1 from public.nextgen_finals_invitations
    where tournament_id=p_tournament_id
      and field_slot=p_field_slot
      and status in ('pending','accepted')
  ) then
    return jsonb_build_object('ok',true,'already_reserved',true,'slot',p_field_slot);
  end if;

  select count(*) into v_refusals
  from public.nextgen_finals_invitations
  where tournament_id=p_tournament_id and status='ai_declined';

  for rec in
    select c.*,row_number() over(order by c.atp_rank,c.player_id)::int as selection_order
    from public.nextgen_finals_candidate_pool(p_tournament_id) c
    where not exists(
      select 1 from public.nextgen_finals_invitations i
      where i.tournament_id=p_tournament_id and i.player_id=c.player_id
    )
    order by c.atp_rank,c.player_id
  loop
    if rec.injury_status<>'Fit' or rec.fitness<45 then
      insert into public.nextgen_finals_invitations(
        tournament_id,player_id,field_slot,atp_rank,selection_order,is_managed,
        status,invited_on,responded_on,refusal_probability,refusal_reason,decision_meta
      ) values(
        p_tournament_id,rec.player_id,p_field_slot,rec.atp_rank,rec.selection_order,rec.is_managed,
        'unavailable',p_invited_on,p_invited_on,1,'physical_unavailable',
        jsonb_build_object('injury_status',rec.injury_status,'fitness',rec.fitness)
      );
      continue;
    end if;

    if rec.is_managed and p_allow_managed_pending then
      select least(t.start_date-2,p_invited_on+7)
      into v_respond_by
      from public.tournaments t where t.id=p_tournament_id;
      v_respond_by:=greatest(p_invited_on,v_respond_by);

      insert into public.nextgen_finals_invitations(
        tournament_id,player_id,field_slot,atp_rank,selection_order,is_managed,
        status,invited_on,respond_by,refusal_probability,refusal_reason
      ) values(
        p_tournament_id,rec.player_id,p_field_slot,rec.atp_rank,rec.selection_order,true,
        'pending',p_invited_on,v_respond_by,null,'managed_decision'
      )
      returning id into v_inv_id;

      insert into public.inbox_items(
        kind,title,body,action_route,game_date,priority,is_read,
        action_type,action_label,action_payload,
        secondary_action_type,secondary_action_label,secondary_action_payload,
        decision_status,related_entity_type,related_entity_id,expires_at
      ) values(
        'selection','Next Gen ATP Finals · sélection',
        rec.player_name||' est appelé pour les Next Gen ATP Finals en tant que #'||
        rec.atp_rank||' ATP parmi les joueurs U21 éligibles. Tu peux accepter ou refuser la sélection.',
        'calendar',p_invited_on,'high',false,
        'respond_nextgen_finals_invitation','Accepter',
        jsonb_build_object('invitation_id',v_inv_id,'decision','accept','player_id',rec.player_id,'tournament_id',p_tournament_id),
        'respond_nextgen_finals_invitation','Refuser',
        jsonb_build_object('invitation_id',v_inv_id,'decision','decline','player_id',rec.player_id,'tournament_id',p_tournament_id),
        'pending','nextgen_finals_invitation',v_inv_id,v_respond_by
      );

      return jsonb_build_object(
        'ok',true,'pending',true,'managed',true,'invitation_id',v_inv_id,
        'player_id',rec.player_id,'slot',p_field_slot,'atp_rank',rec.atp_rank
      );
    end if;

    if rec.is_managed and not p_allow_managed_pending then
      insert into public.nextgen_finals_invitations(
        tournament_id,player_id,field_slot,atp_rank,selection_order,is_managed,
        status,invited_on,responded_on,refusal_probability,refusal_reason
      ) values(
        p_tournament_id,rec.player_id,p_field_slot,rec.atp_rank,rec.selection_order,true,
        'expired',p_invited_on,p_invited_on,null,'managed_window_closed'
      );
      continue;
    end if;

    ai:=public.nextgen_finals_ai_refusal(p_tournament_id,rec.player_id,rec.atp_rank);

    if coalesce((ai->>'accept')::boolean,true)=false and v_refusals<2 then
      insert into public.nextgen_finals_invitations(
        tournament_id,player_id,field_slot,atp_rank,selection_order,is_managed,
        status,invited_on,responded_on,refusal_probability,refusal_reason,decision_meta
      ) values(
        p_tournament_id,rec.player_id,p_field_slot,rec.atp_rank,rec.selection_order,false,
        'ai_declined',p_invited_on,p_invited_on,(ai->>'probability')::numeric,
        coalesce(ai->>'reason','declined'),ai
      );
      v_refusals:=v_refusals+1;
      continue;
    end if;

    insert into public.nextgen_finals_invitations(
      tournament_id,player_id,field_slot,atp_rank,selection_order,is_managed,
      status,invited_on,responded_on,refusal_probability,refusal_reason,decision_meta
    ) values(
      p_tournament_id,rec.player_id,p_field_slot,rec.atp_rank,rec.selection_order,false,
      'accepted',p_invited_on,p_invited_on,(ai->>'probability')::numeric,
      case when coalesce((ai->>'accept')::boolean,true)=false
        then 'refusal_cap_reached'
        else 'accepted'
      end,
      ai||jsonb_build_object('refusal_cap',2,'forced_by_cap',coalesce((ai->>'accept')::boolean,true)=false)
    )
    returning id into v_inv_id;

    return jsonb_build_object(
      'ok',true,'accepted',true,'managed',false,'invitation_id',v_inv_id,
      'player_id',rec.player_id,'slot',p_field_slot,'atp_rank',rec.atp_rank,
      'ai',ai,'refusals_used',v_refusals
    );
  end loop;

  return jsonb_build_object('ok',false,'reason','candidate_pool_exhausted','slot',p_field_slot);
end;
$function$;

create or replace function public.prepare_nextgen_finals_selection(p_tournament_id bigint)
returns jsonb
language plpgsql
set search_path='public'
as $function$
declare
  t public.tournaments%rowtype;
  season int;
  game_date date;
  opens_on date;
  invited_on date;
  slot int;
  r jsonb;
  reserved int;
  accepted int;
  pending int;
  declined int;
begin
  select * into t
  from public.tournaments
  where id=p_tournament_id and circuit='ATP' and category='Next Gen Finals';

  if t.id is null then
    return jsonb_build_object('ok',false,'reason','not_nextgen_finals');
  end if;

  season:=extract(year from t.start_date)::int;
  game_date:=coalesce(
    (select career_date from public.career_state where id='demo'),
    t.start_date-21
  );
  opens_on:=t.start_date-21;

  if game_date<opens_on then
    return jsonb_build_object(
      'ok',true,'not_due',true,'tournament_id',t.id,'season',season,'opens_on',opens_on,
      'rule','Top 8 U21 by ATP ranking · elite players may decline · next eligible moves up'
    );
  end if;

  perform public.refresh_world_nextgen_race(t.start_date-1);
  invited_on:=least(game_date,t.start_date-2);

  for slot in 1..8 loop
    if not exists(
      select 1 from public.nextgen_finals_invitations
      where tournament_id=t.id and field_slot=slot and status in ('pending','accepted')
    ) then
      r:=public.nextgen_fill_finals_slot(t.id,slot,invited_on,true);
      if coalesce((r->>'ok')::boolean,false)=false then
        return jsonb_build_object('ok',false,'reason','slot_fill_failed','slot',slot,'details',r);
      end if;
    end if;
  end loop;

  select count(*) into accepted from public.nextgen_finals_invitations where tournament_id=t.id and status='accepted';
  select count(*) into pending from public.nextgen_finals_invitations where tournament_id=t.id and status='pending';
  select count(*) into declined from public.nextgen_finals_invitations where tournament_id=t.id and status='ai_declined';
  reserved:=accepted+pending;

  return jsonb_build_object(
    'ok',reserved=8,'tournament_id',t.id,'season',season,'opens_on',opens_on,'invited_on',invited_on,
    'accepted',accepted,'pending_managed',pending,'reserved',reserved,'ai_refusals',declined,
    'max_ai_refusals',2,
    'rule','Top 8 U21 by ATP ranking · elite players may decline · next eligible moves up'
  );
end;
$function$;

create or replace function public.resolve_nextgen_finals_invitation(
  p_invitation_id bigint,
  p_accept boolean,
  p_response_date date default null
)
returns jsonb
language plpgsql
set search_path='public'
as $function$
declare
  inv public.nextgen_finals_invitations%rowtype;
  today date;
  repl jsonb;
begin
  select * into inv
  from public.nextgen_finals_invitations
  where id=p_invitation_id
  for update;

  if inv.id is null then return jsonb_build_object('ok',false,'reason','not_found'); end if;
  if not inv.is_managed then return jsonb_build_object('ok',false,'reason','not_managed'); end if;
  if inv.status<>'pending' then return jsonb_build_object('ok',false,'reason','already_resolved','status',inv.status); end if;

  today:=coalesce(p_response_date,(select career_date from public.career_state where id='demo'),current_date);

  if inv.respond_by is not null and today>inv.respond_by then
    update public.nextgen_finals_invitations
    set status='expired',responded_on=today,refusal_reason='deadline_passed',
        decision_meta=jsonb_build_object('decision','expired','date',today),updated_at=now()
    where id=inv.id;

    update public.inbox_items
    set decision_status='resolved',is_read=true
    where related_entity_type='nextgen_finals_invitation' and related_entity_id=inv.id;

    repl:=public.nextgen_fill_finals_slot(inv.tournament_id,inv.field_slot,today,true);
    return jsonb_build_object('ok',false,'reason','expired','replacement',repl);
  end if;

  if p_accept then
    update public.nextgen_finals_invitations
    set status='accepted',responded_on=today,refusal_reason='managed_accept',
        decision_meta=jsonb_build_object('decision','accept','date',today),updated_at=now()
    where id=inv.id;

    update public.inbox_items
    set decision_status='resolved',is_read=true
    where related_entity_type='nextgen_finals_invitation' and related_entity_id=inv.id;

    return jsonb_build_object('ok',true,'status','accepted','player_id',inv.player_id,'slot',inv.field_slot,'atp_rank',inv.atp_rank);
  end if;

  update public.nextgen_finals_invitations
  set status='declined',responded_on=today,refusal_reason='managed_decline',
      decision_meta=jsonb_build_object('decision','decline','date',today),updated_at=now()
  where id=inv.id;

  update public.inbox_items
  set decision_status='resolved',is_read=true
  where related_entity_type='nextgen_finals_invitation' and related_entity_id=inv.id;

  repl:=public.nextgen_fill_finals_slot(inv.tournament_id,inv.field_slot,today,true);

  return jsonb_build_object(
    'ok',true,'status','declined','player_id',inv.player_id,'slot',inv.field_slot,
    'replacement',repl
  );
end;
$function$;

create or replace function public.expire_nextgen_finals_invitations(p_tournament_id bigint)
returns jsonb
language plpgsql
set search_path='public'
as $function$
declare
  inv record;
  r jsonb;
  n int:=0;
begin
  for inv in
    select *
    from public.nextgen_finals_invitations
    where tournament_id=p_tournament_id and status='pending'
    order by field_slot
  loop
    update public.nextgen_finals_invitations
    set status='expired',responded_on=coalesce(respond_by,current_date),
        refusal_reason='event_start_no_response',updated_at=now()
    where id=inv.id;

    update public.inbox_items
    set decision_status='resolved',is_read=true
    where related_entity_type='nextgen_finals_invitation' and related_entity_id=inv.id;

    r:=public.nextgen_fill_finals_slot(p_tournament_id,inv.field_slot,coalesce(inv.respond_by,current_date),false);
    if coalesce((r->>'ok')::boolean,false)=false then
      return jsonb_build_object('ok',false,'reason','replacement_failed','slot',inv.field_slot,'details',r);
    end if;
    n:=n+1;
  end loop;

  return jsonb_build_object('ok',true,'expired',n);
end;
$function$;

drop function if exists public.nextgen_finals_field(bigint);

create function public.nextgen_finals_field(p_tournament_id bigint)
returns table(
  player_id bigint,
  player_name text,
  country text,
  field_slot integer,
  atp_rank integer,
  selection_status text,
  selection_method text,
  is_managed boolean
)
language sql
stable
set search_path='public'
as $function$
  select
    i.player_id,
    p.name,
    p.country,
    i.field_slot,
    i.atp_rank,
    i.status,
    case
      when i.is_managed then 'managed_invitation'
      when i.refusal_reason='refusal_cap_reached' then 'elite_refusal_capped'
      else 'atp_u21_ranking'
    end,
    i.is_managed
  from public.nextgen_finals_invitations i
  join public.players p on p.id=i.player_id
  where i.tournament_id=p_tournament_id
    and i.status in ('accepted','pending')
  order by i.field_slot;
$function$;

create or replace function public.nextgen_finals_player_status(
  p_tournament_id bigint,
  p_player_id bigint
)
returns jsonb
language plpgsql
stable
set search_path='public'
as $function$
declare
  rowv record;
  season int;
  elig boolean;
begin
  select extract(year from start_date)::int into season
  from public.tournaments
  where id=p_tournament_id and circuit='ATP' and category='Next Gen Finals';

  if season is null then return jsonb_build_object('ok',false,'reason','not_nextgen_finals'); end if;
  elig:=public.nextgen_player_eligible(p_player_id,season);

  select * into rowv
  from public.nextgen_finals_invitations
  where tournament_id=p_tournament_id and player_id=p_player_id
  order by id desc limit 1;

  return jsonb_build_object(
    'ok',true,
    'eligible_age',coalesce(elig,false),
    'selected',rowv.status in ('accepted','pending'),
    'status',rowv.status,
    'field_slot',rowv.field_slot,
    'atp_rank',rowv.atp_rank,
    'managed',rowv.is_managed,
    'rule','Top 8 U21 by ATP ranking · elite refusals capped at 2'
  );
end;
$function$;

update public.tournament_format_rules
set wildcard_count=0,
    wildcard_count_max=0,
    source_label='Court Boss Next Gen rule · Top 8 U21 ATP ranking · elite refusal model',
    source_url=null,
    updated_at=now()
where rule_key='NEXTGEN_8';

update public.tournaments
set registration_mode='nextgen_selection',
    main_entry_deadline=null,
    singles_entry_deadline=null,
    qualifying_entry_deadline=null,
    entry_rule_note='Court Boss Next Gen Finals: les 8 meilleurs joueurs U21 selon le classement ATP sont appelés. Les joueurs d’élite peuvent refuser; maximum 2 refus IA par édition, puis le prochain U21 au classement est appelé. Pas d’inscription manuelle. 2 groupes de 4, demi-finales et finale. BO5, sets à 4 jeux, tie-break à 3-3, no-ad, aucun point ATP.'
where circuit='ATP' and category='Next Gen Finals';
