create table if not exists public.world_ranking_baseline_decay (
  player_id bigint primary key references public.players(id) on delete cascade,
  baseline_points integer not null default 0,
  snapshot_date date not null default date '2025-12-01',
  expiry_date date not null default date '2026-11-30',
  source_label text not null default 'ATP baseline 2025-12-01 · linear 52-week decay',
  created_at timestamptz not null default now()
);

create table if not exists public.world_ranking_points (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  tournament_id bigint references public.tournaments(id) on delete cascade,
  label text,
  earned_date date not null,
  expiry_date date not null,
  points integer not null check(points>=0),
  active boolean not null default true,
  source_label text not null default 'Court Boss world simulation',
  created_at timestamptz not null default now(),
  unique(player_id,tournament_id)
);

create index if not exists idx_world_ranking_points_player_active_expiry
  on public.world_ranking_points(player_id,active,expiry_date);
create index if not exists idx_world_ranking_points_expiry_active
  on public.world_ranking_points(expiry_date) where active=true;

alter table public.world_ranking_baseline_decay enable row level security;
alter table public.world_ranking_points enable row level security;
revoke all on table public.world_ranking_baseline_decay from public,anon,authenticated;
revoke all on table public.world_ranking_points from public,anon,authenticated;
grant select,insert,update,delete on table public.world_ranking_baseline_decay to service_role;
grant select,insert,update,delete on table public.world_ranking_points to service_role;

insert into public.world_ranking_baseline_decay(player_id,baseline_points,snapshot_date,expiry_date)
select p.id,greatest(0,coalesce(p.points,0)),date '2025-12-01',date '2026-11-30'
from public.players p
where p.ranking_current=true
  and coalesce(p.data_source,'') not ilike 'hidden duplicate merged into %'
on conflict(player_id) do update set
  baseline_points=excluded.baseline_points,
  snapshot_date=excluded.snapshot_date,
  expiry_date=excluded.expiry_date;

create or replace function public.refresh_world_rankings(p_date date default current_date)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_date date:=coalesce(p_date,current_date);
  v_managed bigint;
  v_updated int:=0;
  v_leader text;
begin
  select managed_player_id into v_managed
  from public.career_state
  where id='demo';

  update public.world_ranking_points
  set active=false
  where active=true and expiry_date<v_date;

  with totals as (
    select
      p.id,
      greatest(0,round(
        coalesce(b.baseline_points,0) *
        case
          when b.player_id is null then 0
          when v_date<=b.snapshot_date then 1
          when v_date>=b.expiry_date then 0
          else (b.expiry_date-v_date)::numeric /
               greatest(1,(b.expiry_date-b.snapshot_date)::numeric)
        end
      )::int) as baseline_remaining,
      coalesce(sum(w.points) filter(where w.active=true and w.earned_date<=v_date and w.expiry_date>=v_date),0)::int as game_points
    from public.players p
    left join public.world_ranking_baseline_decay b on b.player_id=p.id
    left join public.world_ranking_points w on w.player_id=p.id
    where p.ranking_current=true
      and p.id is distinct from v_managed
    group by p.id,b.player_id,b.baseline_points,b.snapshot_date,b.expiry_date
  )
  update public.players p
  set points=greatest(0,t.baseline_remaining+t.game_points),
      ranking_source='Court Boss 52-week world ledger'
  from totals t
  where p.id=t.id;

  get diagnostics v_updated=row_count;

  with ranked as (
    select id,row_number() over(
      order by points desc,current_ability desc,form desc,id
    )::int as new_rank
    from public.players
    where ranking_current=true
  )
  update public.players p
  set ranking=r.new_rank
  from ranked r
  where p.id=r.id;

  insert into public.ranking_history(player_id,snapshot_date,ranking,points)
  select id,v_date,ranking,points
  from public.players
  where ranking_current=true
  on conflict do nothing;

  select name into v_leader
  from public.players
  where ranking_current=true
  order by ranking
  limit 1;

  return jsonb_build_object(
    'date',v_date,
    'updated_players',v_updated,
    'leader',v_leader,
    'model','52-week ledger · decaying 2025 baseline + simulated results'
  );
end;
$$;

revoke execute on function public.refresh_world_rankings(date)
from public,anon,authenticated;
grant execute on function public.refresh_world_rankings(date)
to service_role;
