
-- Court Boss ATP rolling ledger + infinite calendar
-- Consolidated repo migration. The live DB was introduced incrementally; this file
-- records the final idempotent state so repo and database stay aligned.

create table if not exists public.atp_defending_points_ledger (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  source_season integer not null,
  source_event_key text not null,
  tournament_name text not null,
  source_tournament_id text,
  event_date date not null,
  drop_date date not null,
  rank_category text not null,
  result_code text,
  raw_points integer not null default 0,
  points integer not null default 0,
  counting_at_snapshot boolean not null default false,
  is_estimated boolean not null default true,
  source_label text,
  created_at timestamptz not null default now(),
  unique(player_id,source_season,source_event_key)
);

create index if not exists atp_defending_points_player_drop_idx
  on public.atp_defending_points_ledger(player_id,drop_date);
create index if not exists atp_defending_points_drop_idx
  on public.atp_defending_points_ledger(drop_date);

create table if not exists public.atp_ranking_zero_pointers (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  earned_date date not null,
  expiry_date date not null,
  rank_category text not null check(rank_category in ('Grand Slam','M1000','ATP500')),
  reason text,
  replacement_eligible boolean not null default false,
  active boolean not null default true,
  source_label text,
  created_at timestamptz not null default now(),
  unique(player_id,tournament_id)
);

create index if not exists atp_zero_pointer_player_date_idx
  on public.atp_ranking_zero_pointers(player_id,earned_date,expiry_date);


-- atp_historical_result_points(p_category text, p_result text, p_competition_key text, p_name text, p_draw integer)
CREATE OR REPLACE FUNCTION public.atp_historical_result_points(p_category text, p_result text, p_competition_key text DEFAULT NULL::text, p_name text DEFAULT NULL::text, p_draw integer DEFAULT NULL::integer)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
select greatest(0,case
 when p_category='Grand Chelem' then case upper(coalesce(p_result,''))
  when 'W' then 2000 when 'F' then 1300 when 'SF' then 800 when 'QF' then 400
  when 'R4' then 200 when 'R3' then 100 when 'R2' then 50 when 'R1' then 10
  when 'Q3' then 16 when 'Q2' then 8 else 0 end
 when p_category='Masters 1000' then case upper(coalesce(p_result,''))
  when 'W' then 1000 when 'F' then 650 when 'SF' then 400 when 'QF' then 200
  when 'R4' then 100
  when 'R3' then case when coalesce(p_draw,96)>56 then 50 else 100 end
  when 'R2' then case when coalesce(p_draw,96)>56 then 30 else 50 end
  when 'R1' then 10
  when 'Q3' then 16
  when 'Q2' then case when coalesce(p_draw,96)>56 then 10 else 16 end
  else 0 end
 when p_category='ATP Finals' then case upper(coalesce(p_result,''))
  when 'W' then 1500 when 'F' then 1000 when 'SF' then 600 when 'RR' then 200 else 0 end
 when p_category='ATP Tour' and coalesce(p_name,'')='Laver Cup' then 0
 when p_category='ATP Tour' and coalesce(p_name,'')='United Cup' then case upper(coalesce(p_result,''))
  when 'W' then 500 when 'F' then 350 when 'SF' then 250 when 'QF' then 150 when 'RR' then 75 else 0 end
 when p_category='ATP Tour' and (
   coalesce(p_competition_key,'') like 'atp500:%'
   or lower(coalesce(p_name,'')) in (
     'dallas','rotterdam','doha','rio de janeiro','dubai','acapulco',
     'barcelona','munich','hamburg','queen''s club','halle','washington',
     'tokyo','beijing','vienna','basel'
   )
 ) then case upper(coalesce(p_result,''))
  when 'W' then 500 when 'F' then 330 when 'SF' then 200 when 'QF' then 100
  when 'R3' then 50
  when 'R2' then case when coalesce(p_draw,32)>32 then 25 else 50 end
  when 'R1' then 0
  when 'Q2' then case when coalesce(p_draw,32)>32 then 8 else 13 end
  else 0 end
 when p_category='ATP Tour' then case upper(coalesce(p_result,''))
  when 'W' then 250 when 'F' then 165 when 'SF' then 100 when 'QF' then 50
  when 'R3' then 25 when 'R2' then 25 when 'R1' then 0
  when 'Q2' then case when coalesce(p_draw,32)>32 then 4 else 7 end else 0 end
 when p_category='Challenger' then case upper(coalesce(p_result,''))
  when 'W' then 100 when 'F' then 50 when 'SF' then 25 when 'QF' then 14
  when 'R2' then 7 when 'R1' then 0 when 'Q2' then 4 when 'Q1' then 0 else 0 end
 else 0 end);
$function$;

-- atp_historical_rank_category(p_category text, p_competition_key text, p_name text)
CREATE OR REPLACE FUNCTION public.atp_historical_rank_category(p_category text, p_competition_key text DEFAULT NULL::text, p_name text DEFAULT NULL::text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
select case
 when p_category='Grand Chelem' then 'Grand Slam'
 when p_category='Masters 1000' then 'M1000'
 when p_category='ATP Finals' then 'Finals'
 when p_category='ATP Tour' and coalesce(p_name,'')='United Cup' then 'United Cup'
 when p_category='ATP Tour' and coalesce(p_name,'')='Laver Cup' then 'Exhibition'
 when p_category='ATP Tour' and (
   coalesce(p_competition_key,'') like 'atp500:%'
   or lower(coalesce(p_name,'')) in (
     'dallas','rotterdam','doha','rio de janeiro','dubai','acapulco',
     'barcelona','munich','hamburg','queen''s club','halle','washington',
     'tokyo','beijing','vienna','basel'
   )
 ) then 'ATP500'
 when p_category='ATP Tour' then 'ATP250'
 when p_category='Challenger' then 'Challenger'
 else 'Other' end;
$function$;

-- record_atp_zero_pointer(p_player_id bigint, p_tournament_id bigint, p_withdrawal_date date, p_reason text)
CREATE OR REPLACE FUNCTION public.record_atp_zero_pointer(p_player_id bigint, p_tournament_id bigint, p_withdrawal_date date DEFAULT CURRENT_DATE, p_reason text DEFAULT 'withdrawal'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  t public.tournaments%rowtype;
  v_cat text;
  v_earned date;
begin
  select * into t from public.tournaments where id=p_tournament_id;
  if t.id is null then return jsonb_build_object('recorded',false,'reason','tournament_not_found'); end if;

  v_cat:=case
    when t.category='Grand Chelem' then 'Grand Slam'
    when t.category='Masters 1000' then 'M1000'
    when t.category='ATP 500' then 'ATP500'
    else null end;

  if v_cat is null then
    return jsonb_build_object('recorded',false,'reason','not_zero_pointer_category','category',t.category);
  end if;

  if v_cat='ATP500' then
    return jsonb_build_object(
      'recorded',false,'reason','atp500_commitment_penalty_requires_specific_commitment_rule',
      'category',v_cat
    );
  end if;

  v_earned:=coalesce(t.end_date,t.start_date,p_withdrawal_date);

  insert into public.atp_ranking_zero_pointers(
    player_id,tournament_id,earned_date,expiry_date,rank_category,reason,
    replacement_eligible,active,source_label
  )
  values(
    p_player_id,p_tournament_id,v_earned,v_earned+364,v_cat,p_reason,
    v_cat='M1000',true,'Court Boss · ATP mandatory zero pointer'
  )
  on conflict(player_id,tournament_id) do update set
    earned_date=excluded.earned_date,
    expiry_date=excluded.expiry_date,
    rank_category=excluded.rank_category,
    reason=excluded.reason,
    replacement_eligible=excluded.replacement_eligible,
    active=true,
    source_label=excluded.source_label;

  return jsonb_build_object(
    'recorded',true,'player_id',p_player_id,'tournament_id',p_tournament_id,
    'category',v_cat,'earned_date',v_earned,'expiry_date',v_earned+364,
    'replacement_eligible',v_cat='M1000'
  );
end;
$function$;

-- sync_atp_zero_pointers(p_date date)
CREATE OR REPLACE FUNCTION public.sync_atp_zero_pointers(p_date date DEFAULT CURRENT_DATE)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_inserted int:=0;
begin
  insert into public.atp_ranking_zero_pointers(
    player_id,tournament_id,earned_date,expiry_date,rank_category,reason,
    replacement_eligible,active,source_label
  )
  select
    f.player_id,t.id,coalesce(t.end_date,t.start_date),
    coalesce(t.end_date,t.start_date)+364,
    case when t.category='Grand Chelem' then 'Grand Slam' else 'M1000' end,
    coalesce(f.reason,'withdrawal/forfeit'),
    t.category='Masters 1000',
    true,
    'Court Boss · ATP mandatory zero pointer · synced from tournament withdrawal'
  from public.tournament_forfeits f
  join public.tournaments t on t.id=f.tournament_id
  where t.category in ('Grand Chelem','Masters 1000')
    and coalesce(f.withdrawn_on::date,f.created_at::date,t.start_date)<=p_date
    and (
      exists(
        select 1 from public.world_tournament_acceptance_entries a
        where a.tournament_id=t.id and a.player_id=f.player_id
          and coalesce(a.entry_method,'direct') not ilike '%qualif%'
      )
      or exists(
        select 1 from public.entries e
        where e.tournament_id=t.id and e.player_id=f.player_id
          and coalesce(e.entry_method,'direct') not ilike '%qualif%'
      )
    )
  on conflict(player_id,tournament_id) do update set
    active=true,
    reason=excluded.reason,
    source_label=excluded.source_label;

  get diagnostics v_inserted=row_count;

  update public.atp_ranking_zero_pointers
  set active=(expiry_date>=p_date);

  return jsonb_build_object('date',p_date,'synced',v_inserted);
end;
$function$;

-- atp_event_pool(p_player_id bigint, p_date date)
CREATE OR REPLACE FUNCTION public.atp_event_pool(p_player_id bigint, p_date date)
 RETURNS TABLE(event_key text, label text, earned_date date, drop_date date, points integer, rank_category text, source_kind text, estimated boolean)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
with managed_primary as (
 select managed_player_id from public.career_state where id='demo'
),
hist as (
 select l.source_event_key as event_key,l.tournament_name as label,l.event_date as earned_date,
        l.drop_date,l.points,l.rank_category,'historical'::text as source_kind,l.is_estimated as estimated
 from public.atp_defending_points_ledger l
 where l.player_id=p_player_id and l.event_date<=p_date and l.drop_date>=p_date
   and (l.points>=0 or l.rank_category='Reconciliation')
),
zeroes as (
 select 'zero:'||z.tournament_id::text as event_key,
        coalesce(t.name,'Tournoi')||' · zero pointer' as label,
        z.earned_date,z.expiry_date as drop_date,0::integer as points,z.rank_category,
        'zero_pointer'::text as source_kind,false as estimated
 from public.atp_ranking_zero_pointers z
 join public.tournaments t on t.id=z.tournament_id
 where z.player_id=p_player_id and z.active=true
   and z.earned_date<=p_date and z.expiry_date>=p_date
),
world as (
 select 'game:'||w.tournament_id::text as event_key,w.label,w.earned_date,
   case when t.category='ATP Finals'
     then date_trunc('week',w.expiry_date::timestamp)::date+7
     else w.expiry_date end as drop_date,
   w.points,
   case when t.category='Grand Chelem' then 'Grand Slam'
    when t.category='Masters 1000' then 'M1000'
    when t.category='ATP Finals' then 'Finals'
    when t.category='United Cup' then 'United Cup'
    when t.category='ATP 500' then 'ATP500'
    when t.category='ATP 250' then 'ATP250'
    when t.circuit='Challenger' then 'Challenger'
    when t.circuit='ITF' then 'ITF'
    else coalesce(t.category,t.circuit,'Other') end as rank_category,
   'world'::text as source_kind,false as estimated
 from public.world_ranking_points w
 left join public.tournaments t on t.id=w.tournament_id
 where w.player_id=p_player_id
   and w.earned_date<=p_date
   and (
     case when t.category='ATP Finals'
       then date_trunc('week',w.expiry_date::timestamp)::date+7
       else w.expiry_date end
   )>=p_date
   and not exists(
     select 1 from public.user_ranking_points u
     where coalesce(u.player_id,(select managed_player_id from managed_primary))=p_player_id
       and u.tournament_id=w.tournament_id
   )
   and not exists(
     select 1 from public.atp_ranking_zero_pointers z
     where z.player_id=p_player_id and z.tournament_id=w.tournament_id and z.active=true
   )
),
usr as (
 select 'game:'||coalesce(u.tournament_id::text,'legacy:'||u.id::text) as event_key,
        u.label,u.earned_date,
   case when t.category='ATP Finals'
     then date_trunc('week',u.expiry_date::timestamp)::date+7
     else u.expiry_date end as drop_date,
   u.points,
   case when t.category='Grand Chelem' then 'Grand Slam'
    when t.category='Masters 1000' then 'M1000'
    when t.category='ATP Finals' then 'Finals'
    when t.category='United Cup' then 'United Cup'
    when t.category='ATP 500' then 'ATP500'
    when t.category='ATP 250' then 'ATP250'
    when t.circuit='Challenger' then 'Challenger'
    when t.circuit='ITF' then 'ITF'
    else case when u.tournament_id is null then 'Legacy' else coalesce(t.category,t.circuit,'Other') end end as rank_category,
   'managed'::text as source_kind,(u.tournament_id is null) as estimated
 from public.user_ranking_points u
 left join public.tournaments t on t.id=u.tournament_id
 where coalesce(u.player_id,(select managed_player_id from managed_primary))=p_player_id
   and u.earned_date<=p_date
   and (
     case when t.category='ATP Finals'
       then date_trunc('week',u.expiry_date::timestamp)::date+7
       else u.expiry_date end
   )>=p_date
   and (
     u.tournament_id is not null
     or not exists(select 1 from public.atp_defending_points_ledger z where z.player_id=p_player_id)
   )
   and not exists(
     select 1 from public.atp_ranking_zero_pointers z
     where z.player_id=p_player_id and z.tournament_id=u.tournament_id and z.active=true
   )
),
unioned as (
 select * from hist union all select * from zeroes union all select * from world union all select * from usr
),
dedup as (
 select distinct on(event_key) event_key,label,earned_date,drop_date,points,rank_category,source_kind,estimated
 from unioned
 order by event_key,
   case source_kind when 'managed' then 0 when 'zero_pointer' then 1 when 'world' then 2 else 3 end
)
select * from dedup;
$function$;

-- atp_player_breakdown(p_player_id bigint, p_date date)
CREATE OR REPLACE FUNCTION public.atp_player_breakdown(p_player_id bigint, p_date date)
 RETURNS TABLE(event_key text, label text, earned_date date, drop_date date, points integer, rank_category text, counting boolean, counting_reason text, replaced_m1000 boolean, replacement_event boolean, source_kind text, estimated boolean)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
with pool as (select * from public.atp_event_pool(p_player_id,p_date)),
counts as (
 select
   count(*) filter(where rank_category in ('Grand Slam','M1000'))::int mandatory_events,
   count(*) filter(where rank_category not in ('Grand Slam','M1000','Finals','Reconciliation'))::int optional_events
 from pool
),
slot_info as (
 select mandatory_events,optional_events,
        greatest(0,18-mandatory_events)::int optional_slots,
        greatest(0,least(3,optional_events-greatest(0,18-mandatory_events)))::int replacement_capacity
 from counts
),
m_candidates as (
 select p.*,row_number() over(order by p.points asc,p.earned_date asc,p.event_key) rn
 from pool p
 where p.rank_category='M1000'
   and exists(
     select 1 from pool o
     where o.rank_category in ('ATP500','ATP250')
       and o.earned_date>p.earned_date and o.points>p.points
   )
),
replace_m as (
 select m.*
 from m_candidates m cross join slot_info s
 where m.rn<=s.replacement_capacity
),
replacement_candidates as (
 select p.*,row_number() over(order by p.points desc,p.earned_date desc,p.event_key) rn
 from pool p
 where p.rank_category in ('ATP500','ATP250')
   and exists(
     select 1 from replace_m m
     where p.earned_date>m.earned_date and p.points>m.points
   )
),
replace_o as (
 select * from replacement_candidates where rn<=(select count(*) from replace_m)
),
optional_ranked as (
 select p.event_key,row_number() over(order by p.points desc,p.earned_date desc,p.event_key) rn
 from pool p
 where p.rank_category not in ('Grand Slam','M1000','Finals','Reconciliation')
   and not exists(select 1 from replace_o r where r.event_key=p.event_key)
),
classified as (
 select p.*,
   exists(select 1 from replace_m m where m.event_key=p.event_key) replaced_m1000,
   exists(select 1 from replace_o r where r.event_key=p.event_key) replacement_event,
   case
    when p.rank_category='Reconciliation' then true
    when p.rank_category='Grand Slam' then true
    when p.rank_category='M1000' and not exists(select 1 from replace_m m where m.event_key=p.event_key) then true
    when p.rank_category='Finals' then true
    when exists(select 1 from replace_o r where r.event_key=p.event_key) then true
    when exists(
      select 1 from optional_ranked o cross join slot_info s
      where o.event_key=p.event_key and o.rn<=s.optional_slots
    ) then true
    else false end counting
 from pool p
)
select c.event_key,c.label,c.earned_date,c.drop_date,c.points,c.rank_category,c.counting,
 case
  when c.rank_category='Reconciliation' then 'Réconciliation historique avec le total ATP officiel du 01/12/2025'
  when c.rank_category='Grand Slam' then 'Grand Chelem obligatoire'
  when c.rank_category='M1000' and c.replaced_m1000 then 'M1000 remplacé par meilleur ATP 500/250 ultérieur'
  when c.rank_category='M1000' then 'Masters 1000 obligatoire'
  when c.rank_category='Finals' then 'ATP Finals en plus du socle'
  when c.replacement_event then 'Remplacement M1000 (max 3 sur 52 semaines)'
  when c.counting then 'Meilleur résultat optionnel'
  else 'Non comptabilisé actuellement' end,
 c.replaced_m1000,c.replacement_event,c.source_kind,c.estimated
from classified c
order by c.counting desc,c.points desc,c.earned_date desc,c.event_key;
$function$;

-- atp_player_ranking_summary(p_player_id bigint, p_date date)
CREATE OR REPLACE FUNCTION public.atp_player_ranking_summary(p_player_id bigint, p_date date)
 RETURNS TABLE(total_points integer, mandatory_tiebreak_points integer, events_played integer, result_vector integer[], counting_events integer)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
with b as (select * from public.atp_player_breakdown(p_player_id,p_date)),
pool as (select * from public.atp_event_pool(p_player_id,p_date))
select
 coalesce(sum(points) filter(where counting),0)::int,
 coalesce(sum(points) filter(where rank_category in ('Grand Slam','M1000','Finals')),0)::int,
 (select count(*)::int from pool where rank_category<>'Reconciliation'),
 coalesce(array_agg(points order by points desc,earned_date desc)
   filter(where counting and rank_category<>'Reconciliation'),array[]::integer[]),
 count(*) filter(where counting and rank_category<>'Reconciliation')::int
from b;
$function$;

-- atp_points_to_defend(p_player_id bigint, p_date date, p_weeks integer)
CREATE OR REPLACE FUNCTION public.atp_points_to_defend(p_player_id bigint, p_date date, p_weeks integer DEFAULT 52)
 RETURNS TABLE(week_start date, week_end date, points_to_defend integer, events jsonb)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
with weeks as (
 select (date_trunc('week',p_date::timestamp)::date+(g*7))::date week_start,
        (date_trunc('week',p_date::timestamp)::date+(g*7+6))::date week_end
 from generate_series(0,greatest(0,least(104,p_weeks))-1) g
),
b as (
 select * from public.atp_player_breakdown(p_player_id,p_date) where counting=true
)
select w.week_start,w.week_end,coalesce(sum(b.points),0)::int,
 coalesce(jsonb_agg(jsonb_build_object(
   'event_key',b.event_key,'label',b.label,'drop_date',b.drop_date,'points',b.points,
   'category',b.rank_category,'reason',b.counting_reason,'estimated',b.estimated
 ) order by b.drop_date,
   case when b.rank_category='Reconciliation' then 1 else 0 end,
   b.points desc) filter(where b.event_key is not null),'[]'::jsonb)
from weeks w
left join b on b.drop_date between w.week_start and w.week_end
group by w.week_start,w.week_end order by w.week_start;
$function$;


-- Rebuild the 01/12/2025 defending-points portfolio from historical results.
delete from public.atp_defending_points_ledger where source_season=2025;

with history_source as (
 select h.player_id,h.tournament_id,h.tournament_name,h.tournament_date,h.category,h.result_code,
        c.competition_key,c.draw_size,
        public.atp_historical_rank_category(h.category,c.competition_key,h.tournament_name) rank_category,
        public.atp_historical_result_points(h.category,h.result_code,c.competition_key,h.tournament_name,c.draw_size) raw_points
 from public.player_tournament_history h
 left join lateral (
   select ch.competition_key,ch.draw_size
   from public.competition_history ch
   where ch.season=2025 and ch.event_type='singles'
     and lower(regexp_replace(ch.tournament_name,'[^a-z0-9]+','','g'))=
         lower(regexp_replace(h.tournament_name,'[^a-z0-9]+','','g'))
   order by ch.id limit 1
 ) c on true
 where h.season=2025 and h.event_type='singles'
   and h.tournament_date between date '2024-12-02' and date '2025-12-01'
)
insert into public.atp_defending_points_ledger(
 player_id,source_season,source_event_key,tournament_name,source_tournament_id,event_date,drop_date,
 rank_category,result_code,raw_points,points,counting_at_snapshot,is_estimated,source_label
)
select player_id,2025,'hist:'||tournament_id,tournament_name,tournament_id,tournament_date,
       case when rank_category='Finals'
         then date_trunc('week',(tournament_date+364)::timestamp)::date+7
         else tournament_date+364 end,
       rank_category,result_code,raw_points,raw_points,false,
       (rank_category in ('Challenger','United Cup')),
       case when rank_category in ('Challenger','United Cup')
         then 'Court Boss · résultat 2025 réel, niveau/points partiellement estimés'
         else 'Court Boss · résultat 2025 + barème ATP 2026' end
from history_source
where rank_category<>'Exhibition'
on conflict(player_id,source_season,source_event_key) do update set
  tournament_name=excluded.tournament_name,
  event_date=excluded.event_date,
  drop_date=excluded.drop_date,
  rank_category=excluded.rank_category,
  result_code=excluded.result_code,
  raw_points=excluded.raw_points,
  points=excluded.points,
  is_estimated=excluded.is_estimated,
  source_label=excluded.source_label;

delete from public.atp_defending_points_ledger
where source_season=2025 and rank_category='Reconciliation';

with official as (
 select p.id player_id,b.points official_points
 from public.atp_ranking_baseline_2025_12_01 b
 join public.players p on p.sackmann_id=b.source_player_id
),
calc as (
 select o.player_id,o.official_points,coalesce(s.total_points,0) total_points,
        o.official_points-coalesce(s.total_points,0) delta
 from official o
 left join lateral public.atp_player_ranking_summary(o.player_id,date '2025-12-01') s on true
)
insert into public.atp_defending_points_ledger(
 player_id,source_season,source_event_key,tournament_name,source_tournament_id,event_date,drop_date,
 rank_category,result_code,raw_points,points,counting_at_snapshot,is_estimated,source_label
)
select c.player_id,2025,'hist:ranking-reconciliation','Réconciliation classement ATP 01/12/2025',null,
       date '2025-12-01',date '2026-11-30','Reconciliation',null,0,c.delta,true,true,
       'Court Boss · écart résiduel entre historique détaillé et total ATP officiel du 01/12/2025'
from calc c where c.delta<>0
on conflict(player_id,source_season,source_event_key) do update set
  points=excluded.points,drop_date=excluded.drop_date,source_label=excluded.source_label;

update public.atp_defending_points_ledger l
set counting_at_snapshot=b.counting
from (
 select p.id player_id,x.event_key,x.counting
 from public.players p
 cross join lateral public.atp_player_breakdown(p.id,date '2025-12-01') x
 where p.ranking_current=true
) b
where l.player_id=b.player_id and l.source_event_key=b.event_key;


-- recalculate_user_ranking(p_date date)
CREATE OR REPLACE FUNCTION public.recalculate_user_ranking(p_date date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
 v_id bigint;
 v_rank int;
 v_points int;
 s record;
begin
 select managed_player_id into v_id from public.career_state where id='demo';
 if v_id is null then raise exception 'Managed player missing'; end if;

 perform public.refresh_world_rankings(p_date);

 select ranking,points into v_rank,v_points from public.players where id=v_id;
 select * into s from public.atp_player_ranking_summary(v_id,p_date);

 return jsonb_build_object(
   'points',coalesce(v_points,0),'rank',v_rank,'date',p_date,'player_id',v_id,
   'mandatory_points',coalesce(s.mandatory_tiebreak_points,0),
   'events_played',coalesce(s.events_played,0),
   'counting_events',coalesce(s.counting_events,0),
   'base_counting_events',18,
   'ranking_model','ATP_2026_ROLLING_EXACT_TIES'
 );
end;
$function$;

-- recalculate_managed_player_ranking(p_player_id bigint, p_date date)
CREATE OR REPLACE FUNCTION public.recalculate_managed_player_ranking(p_player_id bigint, p_date date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
 v_rank int;
 v_points int;
 s record;
begin
 if p_player_id is null then raise exception 'Managed player missing'; end if;
 perform public.refresh_world_rankings(p_date);
 select ranking,points into v_rank,v_points from public.players where id=p_player_id;
 select * into s from public.atp_player_ranking_summary(p_player_id,p_date);
 return jsonb_build_object(
   'player_id',p_player_id,'points',coalesce(v_points,0),'rank',v_rank,'date',p_date,
   'mandatory_points',coalesce(s.mandatory_tiebreak_points,0),
   'events_played',coalesce(s.events_played,0),
   'counting_events',coalesce(s.counting_events,0),
   'ranking_model','ATP_2026_ROLLING_EXACT_TIES'
 );
end;
$function$;

-- recalculate_managed_player_ranking(p_player_id bigint, p_date date, p_sync_career boolean)
CREATE OR REPLACE FUNCTION public.recalculate_managed_player_ranking(p_player_id bigint, p_date date, p_sync_career boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
 v_result jsonb;
begin
 v_result:=public.recalculate_managed_player_ranking(p_player_id,p_date);
 if coalesce(p_sync_career,false) then
   update public.career_state c
   set points=p.points,singles_rank=p.ranking,career_date=p_date,updated_at=now()
   from public.players p
   where c.id='demo' and p.id=p_player_id and c.managed_player_id=p_player_id;
 end if;
 return v_result;
end;
$function$;

-- refresh_world_rankings(p_date date)
CREATE OR REPLACE FUNCTION public.refresh_world_rankings(p_date date DEFAULT CURRENT_DATE)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
 v_date date:=coalesce(p_date,current_date);
 v_updated int:=0;
 v_leader text;
 v_managed bigint;
 v_zero_sync jsonb;
begin
 perform pg_advisory_xact_lock(94832021);
 v_zero_sync:=public.sync_atp_zero_pointers(v_date);
 select managed_player_id into v_managed from public.career_state where id='demo';

 update public.world_ranking_points w
 set active=(
   case when t.category='ATP Finals'
     then date_trunc('week',w.expiry_date::timestamp)::date+7
     else w.expiry_date end
   >=v_date
 )
 from public.tournaments t
 where t.id=w.tournament_id
   and w.active is distinct from (
     case when t.category='ATP Finals'
       then date_trunc('week',w.expiry_date::timestamp)::date+7
       else w.expiry_date end
     >=v_date
   );

 update public.user_ranking_points u
 set active=(
   case when t.category='ATP Finals'
     then date_trunc('week',u.expiry_date::timestamp)::date+7
     else u.expiry_date end
   >=v_date
 )
 from public.tournaments t
 where t.id=u.tournament_id
   and u.active is distinct from (
     case when t.category='ATP Finals'
       then date_trunc('week',u.expiry_date::timestamp)::date+7
       else u.expiry_date end
     >=v_date
   );

 update public.user_ranking_points
 set active=(expiry_date>=v_date)
 where tournament_id is null
   and active is distinct from (expiry_date>=v_date);

 with managed_ids as (
   select v_managed::bigint id where v_managed is not null
   union
   select player_id from public.academy_roster
   where status='active' and player_id is not null
 ),
 metrics as (
   select p.id,s.total_points,s.mandatory_tiebreak_points,s.events_played,s.result_vector,s.counting_events,
          b.rank baseline_rank
   from public.players p
   cross join lateral public.atp_player_ranking_summary(p.id,v_date) s
   left join public.atp_ranking_baseline_2025_12_01 b on b.source_player_id=p.sackmann_id
   where p.career_status='active'
     and coalesce(p.data_source,'') not ilike 'hidden duplicate merged into %'
     and (
       p.ranking_current=true
       or exists(select 1 from managed_ids m where m.id=p.id)
       or exists(select 1 from public.user_ranking_points u where u.player_id=p.id and u.active=true)
     )
 ),
 simulated as (
   select m.*,
     rank() over(
       order by m.total_points desc,m.mandatory_tiebreak_points desc,
                m.events_played asc,m.result_vector desc
     )::int simulated_rank
   from metrics m
 ),
 ranked as (
   select s.*,
     case when v_date=date '2025-12-01' and s.baseline_rank is not null
       then s.baseline_rank else s.simulated_rank end::int new_rank
   from simulated s
 )
 update public.players p
 set points=r.total_points,ranking=r.new_rank,game_world_rank=r.new_rank,ranking_current=true,
     ranking_source=case
       when v_date=date '2025-12-01' and r.baseline_rank is not null
         then 'ATP official 01/12/2025 snapshot · Court Boss event ledger calibrated'
       else 'Court Boss ATP rolling 52w · ATP 2026 counting + official tie-breaks' end,
     ranking_snapshot_date=v_date,
     previous_ranking=coalesce(p.ranking,p.previous_ranking),
     rank_change=case when p.ranking is null then 0 else p.ranking-r.new_rank end
 from ranked r where p.id=r.id;
 get diagnostics v_updated=row_count;

 if v_managed is not null then
   update public.career_state c
   set points=p.points,singles_rank=p.ranking,career_date=v_date,updated_at=now()
   from public.players p where c.id='demo' and p.id=v_managed;
 end if;

 insert into public.ranking_history(player_id,snapshot_date,ranking,points)
 select id,v_date,ranking,points from public.players
 where ranking_current=true and career_status='active'
   and coalesce(data_source,'') not ilike 'hidden duplicate merged into %'
 on conflict do nothing;

 select name into v_leader from public.players
 where ranking_current=true and career_status='active'
 order by ranking nulls last,name limit 1;

 return jsonb_build_object(
   'date',v_date,'updated_players',v_updated,'leader',v_leader,
   'zero_pointer_sync',v_zero_sync,
   'model','ATP 2026 rolling 52w · dynamic slots · max 3 M1000 replacements · official ties'
 );
end;
$function$;

-- ensure_calendar_season(p_year integer)
CREATE OR REPLACE FUNCTION public.ensure_calendar_season(p_year integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_template_year integer:=2026;
  v_offset integer;
  v_existing integer:=0;
  v_inserted integer:=0;
  v_lowtier integer:=0;
begin
  if p_year<2026 then
    return jsonb_build_object('year',p_year,'inserted',0,'reason','historical_year');
  end if;

  select count(*) into v_existing
  from public.tournaments
  where extract(year from start_date)=p_year and is_active=true;

  if p_year=2026 then
    return jsonb_build_object('year',p_year,'existing',v_existing,'inserted',0,'template',true);
  end if;

  v_offset :=
    date_trunc('week',make_date(p_year,1,4)::timestamp)::date
    - date_trunc('week',make_date(v_template_year,1,4)::timestamp)::date;

  perform pg_advisory_xact_lock(94832027);

  with src as (
    select t.*
    from public.tournaments t
    where extract(year from t.start_date)=v_template_year
      and t.is_active=true
  ),
  missing as (
    select s.*
    from src s
    where not exists(
      select 1
      from public.tournaments x
      where extract(year from x.start_date)=p_year
        and x.is_active=true
        and (
          (s.competition_key is not null and x.competition_key=s.competition_key)
          or
          (s.competition_key is null
           and coalesce(s.history_group,'')<>'' and x.history_group=s.history_group)
          or
          (s.competition_key is null and coalesce(s.history_group,'')=''
           and lower(x.name)=lower(s.name)
           and coalesce(x.category,'')=coalesce(s.category,'')
           and coalesce(x.circuit,'')=coalesce(s.circuit,''))
        )
    )
  )
  insert into public.tournaments(
    name,city,country,surface,level,start_date,end_date,
    singles,doubles,circuit,category,prize_money,draw_size,is_verified,source_url,source_note,
    indoor,venue,is_active,environment,official_season,
    image_url,image_source_url,image_source_label,
    singles_entry_deadline,qualifying_entry_deadline,doubles_entry_deadline,
    singles_draw_size,qualifying_draw_size,doubles_draw_size,winner_points,
    entry_rule_code,entry_rule_note,registration_mode,
    projected_direct_cut,projected_qual_cut,cut_is_projection,
    doubles_onsite_deadline,doubles_entry_method,
    history_group,competition_key,prestige,competition_history_label,
    logo_url,logo_source_url,logo_source_label,
    court_speed,court_speed_source,altitude_m,environment_profile,
    qualifying_start_date,qualifying_end_date,
    prize_currency,prize_money_is_estimate,prize_source_label,prize_source_url,
    singles_prize_by_result,qualifying_prize_by_result,doubles_prize_by_result,
    junior_draw_format,
    singles_withdrawal_deadline,freeze_deadline,performance_bye_slots,performance_bye_source_event,
    main_draw_start_date,main_entry_deadline,withdrawal_deadline,qualifying_signin_date,
    schedule_source_label,
    singles_prize_is_estimate,qualifying_prize_is_estimate,doubles_prize_is_estimate,prize_breakdown_is_estimate,
    prize_format,special_prize_components,prize_total_kind,prize_note,
    late_entry_slots,late_entry_deadline,late_entry_source_label
  )
  select
    n.name,n.city,n.country,n.surface,n.level,
    n.start_date+v_offset,
    case when n.end_date is null then null else n.end_date+v_offset end,
    n.singles,n.doubles,n.circuit,n.category,n.prize_money,n.draw_size,
    false,n.source_url,
    'Court Boss · calendrier auto-généré depuis le patron 2026 · saison '||p_year,
    n.indoor,n.venue,true,n.environment,p_year,
    n.image_url,n.image_source_url,n.image_source_label,
    case when n.singles_entry_deadline is null then null else n.singles_entry_deadline+v_offset end,
    case when n.qualifying_entry_deadline is null then null else n.qualifying_entry_deadline+v_offset end,
    case when n.doubles_entry_deadline is null then null else n.doubles_entry_deadline+v_offset end,
    n.singles_draw_size,n.qualifying_draw_size,n.doubles_draw_size,n.winner_points,
    n.entry_rule_code,n.entry_rule_note,n.registration_mode,
    n.projected_direct_cut,n.projected_qual_cut,true,
    case when n.doubles_onsite_deadline is null then null else n.doubles_onsite_deadline+v_offset end,
    n.doubles_entry_method,
    n.history_group,n.competition_key,n.prestige,n.competition_history_label,
    n.logo_url,n.logo_source_url,n.logo_source_label,
    n.court_speed,n.court_speed_source,n.altitude_m,n.environment_profile,
    case when n.qualifying_start_date is null then null else n.qualifying_start_date+v_offset end,
    case when n.qualifying_end_date is null then null else n.qualifying_end_date+v_offset end,
    n.prize_currency,true,n.prize_source_label,n.prize_source_url,
    n.singles_prize_by_result,n.qualifying_prize_by_result,n.doubles_prize_by_result,
    n.junior_draw_format,
    case when n.singles_withdrawal_deadline is null then null else n.singles_withdrawal_deadline+v_offset end,
    case when n.freeze_deadline is null then null else n.freeze_deadline+v_offset end,
    n.performance_bye_slots,n.performance_bye_source_event,
    case when n.main_draw_start_date is null then null else n.main_draw_start_date+v_offset end,
    case when n.main_entry_deadline is null then null else n.main_entry_deadline+v_offset end,
    case when n.withdrawal_deadline is null then null else n.withdrawal_deadline+v_offset end,
    case when n.qualifying_signin_date is null then null else n.qualifying_signin_date+v_offset end,
    'Court Boss infinite calendar · template 2026',
    true,true,true,true,
    n.prize_format,n.special_prize_components,n.prize_total_kind,n.prize_note,
    n.late_entry_slots,
    case when n.late_entry_deadline is null then null else n.late_entry_deadline+v_offset end,
    n.late_entry_source_label
  from missing n;

  get diagnostics v_inserted=row_count;
  v_lowtier:=public.generate_fictional_tournaments(p_year);

  return jsonb_build_object(
    'year',p_year,
    'template_year',v_template_year,
    'existing_before',v_existing,
    'cloned',v_inserted,
    'fictional_low_tier',v_lowtier,
    'total_after',(
      select count(*) from public.tournaments
      where extract(year from start_date)=p_year and is_active=true
    )
  );
end;
$function$;

-- rollover_season(p_new_year integer)
CREATE OR REPLACE FUNCTION public.rollover_season(p_new_year integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  c career_state%rowtype;
  title_count int;
  final_count int;
  prize numeric;
  retired_count int:=0;
  processed_count int:=0;
  newgen_result jsonb;
  ncaa_result jsonb;
  lifecycle_result jsonb;
  calendar_result jsonb;
  next_calendar_result jsonb;
  ranking_result jsonb;
begin
  select * into c from career_state where id='demo';
  if not found then raise exception 'Career not found'; end if;

  calendar_result:=public.ensure_calendar_season(p_new_year);
  next_calendar_result:=public.ensure_calendar_season(p_new_year+1);

  select count(*) filter(where user_round='Champion'),
         count(*) filter(where user_round in ('Champion','F')),
         coalesce(sum(user_prize),0)
    into title_count,final_count,prize
  from tournament_runs
  where extract(year from played_at)=c.season_year;

  insert into season_history(season_year,final_rank,doubles_rank,titles,finals,prize_money,points)
  values(c.season_year,c.singles_rank,c.doubles_rank,title_count,final_count,prize,c.points)
  on conflict(season_year) do update set
    final_rank=excluded.final_rank,doubles_rank=excluded.doubles_rank,titles=excluded.titles,
    finals=excluded.finals,prize_money=excluded.prize_money,points=excluded.points;

  update players
  set age=case
    when birth_date is not null then extract(year from age(make_date(p_new_year,1,5),birth_date))::int
    when age is not null then age+1
    else null end
  where birth_date is not null or age is not null;

  select public.advance_ncaa_lifecycle(p_new_year) into ncaa_result;

  update players
  set current_ability=greatest(30,least(potential,
        current_ability+case
          when age is not null and age<=23 and potential>current_ability and ((id+p_new_year)%4)=0 then 1
          when age is not null and age>=34 and ((id+p_new_year)%3)=0 then -1
          else 0 end)),
      potential=greatest(current_ability,
        potential-case when age is not null and age>=30 and ((id+p_new_year)%5)=0 then 1 else 0 end)
  where ranking_current=true;

  get diagnostics processed_count=row_count;

  select public.refresh_player_career_lifecycle(make_date(p_new_year,1,5))
    into lifecycle_result;
  retired_count:=coalesce((lifecycle_result->>'retired')::int,0);

  select public.generate_newgens(p_new_year) into newgen_result;

  update career_state
  set season_year=p_new_year,age=age+1,week=1,career_date=make_date(p_new_year,1,5),
      fatigue=greatest(5,fatigue-20),fitness=least(100,fitness+10),morale=least(100,morale+5),
      injury_status='Fit',updated_at=now()
  where id='demo';

  update college_career_state
  set eligibility_years=greatest(0,eligibility_years-1),
      academic_progress=greatest(45,academic_progress-5),
      coach_trust=greatest(40,coach_trust-4)
  where player_id is not null
    and status in ('committed','active');

  update sponsor_offers set status='available' where status='declined';

  ranking_result:=public.refresh_world_rankings(make_date(p_new_year,1,5));

  return jsonb_build_object(
    'new_year',p_new_year,
    'retired_players',retired_count,'processed_players',processed_count,
    'newgens',newgen_result,'ncaa_lifecycle',ncaa_result,'career_lifecycle',lifecycle_result,
    'calendar',calendar_result,'next_calendar',next_calendar_result,
    'ranking',ranking_result,
    'previous_titles',title_count,'previous_prize',prize
  );
end;
$function$;


grant execute on function public.atp_event_pool(bigint,date) to anon,authenticated,service_role;
grant execute on function public.atp_player_breakdown(bigint,date) to anon,authenticated,service_role;
grant execute on function public.atp_player_ranking_summary(bigint,date) to anon,authenticated,service_role;
grant execute on function public.atp_points_to_defend(bigint,date,integer) to anon,authenticated,service_role;
grant execute on function public.record_atp_zero_pointer(bigint,bigint,date,text) to service_role;
grant execute on function public.ensure_calendar_season(integer) to service_role;
