-- Court Boss Legacy world news v10
-- World-record breakthroughs, Slam milestones, Player of the Year stories,
-- all-time Legacy threshold crossings, and idempotent news publication.

create table if not exists public.court_boss_world_story_log (
  id bigint generated by default as identity primary key,
  story_key text not null unique,
  event_date date not null,
  player_id bigint references public.players(id) on delete set null,
  story_type text not null,
  body text not null,
  metadata jsonb not null default '{}'::jsonb,
  news_item_id bigint,
  created_at timestamptz not null default now()
);

alter table public.court_boss_world_story_log enable row level security;
revoke all on public.court_boss_world_story_log from public,anon,authenticated;
grant select,insert,update,delete on public.court_boss_world_story_log to service_role;

create index if not exists idx_cb_world_story_date
  on public.court_boss_world_story_log(event_date desc,story_type);
create index if not exists idx_cb_world_story_player
  on public.court_boss_world_story_log(player_id,event_date desc);

create or replace function public.court_boss_legacy_leaderboard(p_date date)
returns table(
  all_time_rank bigint,
  player_id bigint,
  player_name text,
  country text,
  legacy_score bigint,
  titles bigint,
  grand_slams bigint,
  masters bigint,
  tour_finals bigint,
  wins bigint,
  losses bigint,
  weeks_no1 bigint,
  player_of_year bigint
)
language sql
stable
security invoker
set search_path to ''
as $function$
with future_titles as (
  select pt.player_id,
    count(*)::bigint titles,
    count(*) filter(where public.cb_record_event_key(pt.tournament_name) in ('australian_open','roland_garros','wimbledon','us_open'))::bigint slams,
    count(*) filter(where coalesce(pt.level,'') ilike '%1000%')::bigint masters,
    count(*) filter(where coalesce(pt.level,'') ilike '%ATP Finals%'
      or lower(coalesce(pt.tournament_name,'')) like '%tour finals%'
      or lower(coalesce(pt.tournament_name,'')) like '%atp finals%'
      or lower(coalesce(pt.tournament_name,'')) like '%masters cup%')::bigint finals
  from public.player_titles pt
  where pt.event_type='singles'
    and pt.title_date>date '2025-12-01'
    and pt.title_date<=coalesce(p_date,date '2025-12-01')
  group by pt.player_id
),
future_stats as (
  select s.player_id,
    count(*) filter(where s.won)::bigint wins,
    count(*) filter(where not s.won)::bigint losses
  from public.court_boss_match_stat_lines s
  where s.match_date>date '2025-12-01'
    and s.match_date<=coalesce(p_date,date '2025-12-01')
  group by s.player_id
),
future_no1 as (
  select rh.player_id,count(*)::bigint weeks_no1
  from public.ranking_history rh
  where rh.snapshot_date>date '2025-12-01'
    and rh.snapshot_date<=coalesce(p_date,date '2025-12-01')
    and rh.ranking=1
  group by rh.player_id
),
future_awards as (
  select a.player_id,
    count(*) filter(where a.award_code='player_of_year' and a.award_rank=1)::bigint poy
  from public.court_boss_player_awards a
  where a.season>2025
    and a.season<=extract(year from coalesce(p_date,date '2025-12-01'))::int
  group by a.player_id
),
historical_poy as (
  select p.id player_id,count(y.season)::bigint poy
  from public.players p
  join public.court_boss_year_end_no1_reference y on lower(y.player_name)=lower(p.name)
  where y.season<=least(2025,extract(year from coalesce(p_date,date '2025-12-01'))::int)
    and coalesce(p.data_source,'') not ilike '%hidden duplicate merged into%'
  group by p.id
),
scored as (
  select p.id,p.name,p.country,
    (coalesce(h.titles,0)+coalesce(ft.titles,0))::bigint titles,
    (coalesce(h.grand_slams,0)+coalesce(ft.slams,0))::bigint slams,
    (coalesce(h.masters,0)+coalesce(ft.masters,0))::bigint masters,
    (coalesce(h.tour_finals,0)+coalesce(ft.finals,0))::bigint finals,
    (greatest(coalesce(h.wins,0),coalesce(pcs.wins,0))+coalesce(fs.wins,0))::bigint wins,
    (greatest(coalesce(h.losses,0),coalesce(pcs.losses,0))+coalesce(fs.losses,0))::bigint losses,
    (coalesce(p.weeks_at_no1,0)+coalesce(fn.weeks_no1,0))::bigint weeks_no1,
    (coalesce(hp.poy,0)+coalesce(fa.poy,0))::bigint poy,
    (
      (coalesce(h.grand_slams,0)+coalesce(ft.slams,0))*10000
      +(coalesce(h.tour_finals,0)+coalesce(ft.finals,0))*2200
      +(coalesce(h.masters,0)+coalesce(ft.masters,0))*1200
      +greatest(
        (coalesce(h.titles,0)+coalesce(ft.titles,0))
        -(coalesce(h.grand_slams,0)+coalesce(ft.slams,0))
        -(coalesce(h.masters,0)+coalesce(ft.masters,0))
        -(coalesce(h.tour_finals,0)+coalesce(ft.finals,0)),0
      )*180
      +(greatest(coalesce(h.wins,0),coalesce(pcs.wins,0))+coalesce(fs.wins,0))*2
      +(coalesce(p.weeks_at_no1,0)+coalesce(fn.weeks_no1,0))*8
      +(coalesce(hp.poy,0)+coalesce(fa.poy,0))*1500
    )::bigint legacy_score
  from public.players p
  left join public.history_player_scores h on h.id=p.id
  left join public.player_career_stats pcs on pcs.player_id=p.id
  left join future_titles ft on ft.player_id=p.id
  left join future_stats fs on fs.player_id=p.id
  left join future_no1 fn on fn.player_id=p.id
  left join future_awards fa on fa.player_id=p.id
  left join historical_poy hp on hp.player_id=p.id
  where coalesce(p.data_source,'') not ilike '%hidden duplicate merged into%'
),
eligible as (select * from scored where legacy_score>0)
select
  rank() over(order by legacy_score desc,slams desc,titles desc,wins desc,id)::bigint,
  id::bigint,name,country,legacy_score,titles,slams,masters,finals,wins,losses,weeks_no1,poy
from eligible
order by legacy_score desc,slams desc,titles desc,wins desc,id;
$function$;

create or replace function public.court_boss_all_time_snapshot(p_player_id bigint,p_date date)
returns jsonb
language sql
stable
security invoker
set search_path to ''
as $function$
select coalesce(
  (
    select jsonb_build_object(
      'rank',l.all_time_rank,
      'pool',(select count(*) from public.court_boss_legacy_leaderboard(p_date)),
      'score',l.legacy_score,'titles',l.titles,'grand_slams',l.grand_slams,
      'masters',l.masters,'tour_finals',l.tour_finals,'wins',l.wins,'losses',l.losses,
      'weeks_no1',l.weeks_no1,'player_of_year',l.player_of_year,
      'tier',case
        when l.all_time_rank<=3 then 'GOAT tier'
        when l.all_time_rank<=10 then 'Panthéon'
        when l.all_time_rank<=50 then 'Légende'
        when l.all_time_rank<=200 then 'Élite historique'
        else 'Référence historique'
      end
    )
    from public.court_boss_legacy_leaderboard(p_date) l
    where l.player_id=p_player_id
  ),
  jsonb_build_object(
    'rank',null,'pool',(select count(*) from public.court_boss_legacy_leaderboard(p_date)),
    'score',0,'titles',0,'grand_slams',0,'masters',0,'tour_finals',0,
    'wins',0,'losses',0,'weeks_no1',0,'player_of_year',0,'tier','En construction'
  )
);
$function$;

create or replace function public.court_boss_publish_world_story(
  p_story_key text,p_event_date date,p_player_id bigint,p_story_type text,p_body text,
  p_metadata jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security invoker
set search_path to ''
as $function$
declare v_log_id bigint; v_news_id bigint;
begin
  if coalesce(trim(p_story_key),'')='' or coalesce(trim(p_body),'')='' then return false; end if;
  insert into public.court_boss_world_story_log(story_key,event_date,player_id,story_type,body,metadata)
  values(p_story_key,coalesce(p_event_date,current_date),p_player_id,
    coalesce(nullif(p_story_type,''),'legacy'),p_body,coalesce(p_metadata,'{}'::jsonb))
  on conflict(story_key) do nothing returning id into v_log_id;
  if v_log_id is null then return false; end if;
  insert into public.news_items(body) values(p_body) returning id into v_news_id;
  update public.court_boss_world_story_log set news_item_id=v_news_id where id=v_log_id;
  return true;
end;
$function$;

create or replace function public.court_boss_publish_record_occurrence_news(p_occurrence_id bigint)
returns boolean
language plpgsql
security invoker
set search_path to ''
as $function$
declare
  r public.record_occurrences%rowtype;
  c public.record_catalog%rowtype;
  v_body text;
  v_key text;
begin
  select * into r from public.record_occurrences where id=p_occurrence_id;
  if r.id is null or r.achieved_on<=date '2025-12-01' or coalesce(r.source_type,'')<>'career' then return false; end if;
  select * into c from public.record_catalog where code=r.record_code;
  if c.code is null then return false; end if;

  if c.record_type in ('numeric','dynamic') and c.baseline_value is not null and r.value is not null and r.value>=c.baseline_value then
    if r.value>c.baseline_value then
      v_body:='Nouveau record mondial : '||r.player_name||' efface '||coalesce(c.baseline_holder,'l’ancienne référence')
        ||' avec '||trim(to_char(r.value,'FM999999990.##'))||case when c.unit is not null then ' '||c.unit else '' end
        ||' · '||c.name||'.';
      v_key:='world_record:'||r.record_code||':'||r.player_id||':'||trim(to_char(r.value,'FM999999990.##'));
    else
      v_body:=r.player_name||' égale le record de '||coalesce(c.baseline_holder,'référence')
        ||' : '||trim(to_char(r.value,'FM999999990.##'))||case when c.unit is not null then ' '||c.unit else '' end
        ||' · '||c.name||'.';
      v_key:='record_equal:'||r.record_code||':'||r.player_id||':'||trim(to_char(r.value,'FM999999990.##'));
    end if;
  elsif c.record_type in ('achievement','challenge') and c.rarity in ('mythic','legendary') then
    v_body:=case when c.rarity='mythic'
      then r.player_name||' signe un exploit historique : '
      else r.player_name||' ajoute un exploit majeur à sa carrière : ' end
      ||c.name||case when coalesce(r.label,'')<>'' then ' · '||r.label else '' end||'.';
    v_key:='achievement:'||r.record_code||':'||r.player_id||':'||coalesce(r.season,-1);
  else
    return false;
  end if;

  return public.court_boss_publish_world_story(
    v_key,r.achieved_on,r.player_id,
    case when c.record_type in ('numeric','dynamic') then 'world_record' else 'achievement' end,
    v_body,jsonb_build_object(
      'record_occurrence_id',r.id,'record_code',r.record_code,'record_name',c.name,
      'rarity',c.rarity,'value',r.value,'baseline_value',c.baseline_value,'baseline_holder',c.baseline_holder
    )
  );
end;
$function$;

create or replace function public.court_boss_record_occurrence_news_trigger()
returns trigger language plpgsql security invoker set search_path to ''
as $function$
begin
  perform public.court_boss_publish_record_occurrence_news(new.id);
  return new;
end;
$function$;

drop trigger if exists trg_cb_record_occurrence_world_news on public.record_occurrences;
create trigger trg_cb_record_occurrence_world_news
after insert on public.record_occurrences
for each row execute function public.court_boss_record_occurrence_news_trigger();

create or replace function public.court_boss_publish_legacy_rank_story(
  p_player_id bigint,p_event_date date,p_reason text default null
)
returns boolean
language plpgsql
security invoker
set search_path to ''
as $function$
declare
  v_before record; v_after record; v_displaced text; v_body text; v_key text; v_threshold int;
begin
  if p_event_date<=date '2025-12-01' then return false; end if;
  select * into v_before from public.court_boss_legacy_leaderboard(p_event_date-1) where player_id=p_player_id;
  select * into v_after from public.court_boss_legacy_leaderboard(p_event_date) where player_id=p_player_id;
  if v_after.player_id is null or v_after.all_time_rank is null then return false; end if;

  v_threshold:=case
    when v_after.all_time_rank=1 and coalesce(v_before.all_time_rank,999999)>1 then 1
    when v_after.all_time_rank<=3 and coalesce(v_before.all_time_rank,999999)>3 then 3
    when v_after.all_time_rank<=5 and coalesce(v_before.all_time_rank,999999)>5 then 5
    when v_after.all_time_rank<=10 and coalesce(v_before.all_time_rank,999999)>10 then 10
    when v_after.all_time_rank<=20 and coalesce(v_before.all_time_rank,999999)>20 then 20
    else null end;
  if v_threshold is null then return false; end if;

  select player_name into v_displaced
  from public.court_boss_legacy_leaderboard(p_event_date-1)
  where all_time_rank=v_after.all_time_rank and player_id<>p_player_id
  order by legacy_score desc limit 1;

  v_body:=case when v_threshold=1
    then v_after.player_name||' prend la tête du classement Legacy all-time'
    else v_after.player_name||' entre dans le Top '||v_threshold||' du classement Legacy all-time' end
    ||case when v_displaced is not null then ' en dépassant '||v_displaced else '' end
    ||case when coalesce(trim(p_reason),'')<>'' then ' après '||trim(p_reason) else '' end||'.';
  v_key:='legacy_top_'||v_threshold||':'||p_player_id;

  return public.court_boss_publish_world_story(
    v_key,p_event_date,p_player_id,'legacy_rank',v_body,
    jsonb_build_object('before_rank',v_before.all_time_rank,'after_rank',v_after.all_time_rank,
      'threshold',v_threshold,'displaced_player',v_displaced,'reason',p_reason,'legacy_score',v_after.legacy_score)
  );
end;
$function$;

create or replace function public.court_boss_publish_title_legacy_story(
  p_player_id bigint,p_title_date date,p_tournament_name text,p_level text
)
returns jsonb
language plpgsql
security invoker
set search_path to ''
as $function$
declare
  v_event_key text; v_name text; v_country text; v_slams bigint:=0; v_club bigint:=0;
  v_event_titles bigint:=0; v_catalog_code text; v_catalog public.record_catalog%rowtype; v_story_count int:=0;
begin
  if p_title_date<=date '2025-12-01' then return jsonb_build_object('ok',true,'published',0,'reason','baseline_cutoff'); end if;
  select name,country into v_name,v_country from public.players where id=p_player_id;
  if v_name is null then return jsonb_build_object('ok',false,'reason','player_not_found'); end if;
  v_event_key:=public.cb_record_event_key(p_tournament_name);

  if public.court_boss_publish_legacy_rank_story(p_player_id,p_title_date,'son titre à '||coalesce(p_tournament_name,'un tournoi majeur')) then
    v_story_count:=v_story_count+1;
  end if;

  if v_event_key in ('australian_open','roland_garros','wimbledon','us_open') then
    select coalesce(grand_slams,0) into v_slams
    from public.court_boss_legacy_leaderboard(p_title_date) where player_id=p_player_id;

    if v_slams in (1,5,10,15,20,24,25,30) then
      select count(*) into v_club from public.court_boss_legacy_leaderboard(p_title_date) where grand_slams>=v_slams;
      if public.court_boss_publish_world_story(
        'slam_milestone:'||p_player_id||':'||v_slams,p_title_date,p_player_id,'slam_milestone',
        v_name||' atteint '||v_slams||' titre'||case when v_slams>1 then 's' else '' end
          ||' du Grand Chelem à '||coalesce(p_tournament_name,'un Majeur')
          ||case when v_slams>=5 then ' et rejoint le club des '||v_club||' joueurs à ce niveau dans l’histoire Court Boss' else '' end||'.',
        jsonb_build_object('grand_slams',v_slams,'club_size',v_club,'tournament',p_tournament_name)
      ) then v_story_count:=v_story_count+1; end if;
    end if;

    if v_slams>=24 and not exists(
      select 1 from public.record_occurrences
      where record_code='grand_slam_titles_career' and player_id=p_player_id and coalesce(value,0)>=v_slams
    ) then
      insert into public.record_occurrences(record_code,player_id,player_name,country,season,achieved_on,value,label,source_type,source_label,source_url,metadata)
      values('grand_slam_titles_career',p_player_id,v_name,v_country,extract(year from p_title_date)::int,p_title_date,
        v_slams,v_slams||' Majeurs','career','Court Boss · Legacy news v1','',jsonb_build_object('tournament',p_tournament_name));
    end if;

    v_catalog_code:=case v_event_key
      when 'australian_open' then 'major_event_ao'
      when 'roland_garros' then 'major_event_rg'
      when 'wimbledon' then 'major_event_wimbledon'
      when 'us_open' then 'major_event_us_open_open_era' else null end;

    if v_catalog_code is not null then
      select * into v_catalog from public.record_catalog where code=v_catalog_code;
      select count(*) into v_event_titles
      from public.player_titles pt
      where pt.player_id=p_player_id and pt.event_type='singles' and pt.title_date<=p_title_date
        and public.cb_record_event_key(pt.tournament_name)=v_event_key;
      if v_catalog.code is not null and v_catalog.baseline_value is not null and v_event_titles>=v_catalog.baseline_value
        and not exists(select 1 from public.record_occurrences
          where record_code=v_catalog_code and player_id=p_player_id and coalesce(value,0)>=v_event_titles)
      then
        insert into public.record_occurrences(record_code,player_id,player_name,country,season,achieved_on,value,label,source_type,source_label,source_url,metadata)
        values(v_catalog_code,p_player_id,v_name,v_country,extract(year from p_title_date)::int,p_title_date,
          v_event_titles,v_event_titles||' titres · '||p_tournament_name,'career','Court Boss · Legacy news v1','',
          jsonb_build_object('tournament',p_tournament_name));
      end if;
    end if;
  end if;

  if coalesce(p_level,'') ilike '%ATP Finals%' or lower(coalesce(p_tournament_name,'')) like '%atp finals%'
     or lower(coalesce(p_tournament_name,'')) like '%tour finals%' then
    select count(*) into v_event_titles
    from public.player_titles pt
    where pt.player_id=p_player_id and pt.event_type='singles' and pt.title_date<=p_title_date
      and (coalesce(pt.level,'') ilike '%ATP Finals%'
        or lower(coalesce(pt.tournament_name,'')) like '%atp finals%'
        or lower(coalesce(pt.tournament_name,'')) like '%tour finals%'
        or lower(coalesce(pt.tournament_name,'')) like '%masters cup%');
    if v_event_titles>=7 and not exists(
      select 1 from public.record_occurrences where record_code='atp_finals_titles_career'
        and player_id=p_player_id and coalesce(value,0)>=v_event_titles
    ) then
      insert into public.record_occurrences(record_code,player_id,player_name,country,season,achieved_on,value,label,source_type,source_label,source_url,metadata)
      values('atp_finals_titles_career',p_player_id,v_name,v_country,extract(year from p_title_date)::int,p_title_date,
        v_event_titles,v_event_titles||' titres ATP Finals','career','Court Boss · Legacy news v1','',
        jsonb_build_object('tournament',p_tournament_name));
    end if;
  end if;

  return jsonb_build_object('ok',true,'published',v_story_count,'player_id',p_player_id,'date',p_title_date);
end;
$function$;

create or replace function public.court_boss_record_title_trigger()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if new.event_type='singles' and new.title_date>date '2025-12-01' then
    perform public.sync_court_boss_player_records(new.player_id,new.title_date);
    perform public.court_boss_publish_title_legacy_story(new.player_id,new.title_date,new.tournament_name,new.level);
  end if;
  return new;
end;
$function$;

create or replace function public.court_boss_award_world_news_trigger()
returns trigger
language plpgsql
security invoker
set search_path to ''
as $function$
declare v_date date; v_count bigint:=0;
begin
  if new.award_rank<>1 or new.season<=2025 then return new; end if;
  v_date:=make_date(new.season,12,31);
  if new.award_code='player_of_year' then
    perform public.court_boss_publish_world_story(
      'player_of_year:'||new.season||':'||new.player_id,v_date,new.player_id,'award',
      new.player_name||' est sacré joueur de l’année '||new.season||'.',
      jsonb_build_object('award_code',new.award_code,'season',new.season,'score',new.score)
    );
    perform public.court_boss_publish_legacy_rank_story(new.player_id,v_date,'son titre de joueur de l’année '||new.season);

    select coalesce((select count(*) from public.court_boss_year_end_no1_reference y where lower(y.player_name)=lower(new.player_name)),0)
      +coalesce((select count(*) from public.court_boss_player_awards a
        where a.player_id=new.player_id and a.award_code='player_of_year' and a.award_rank=1 and a.season>2025 and a.season<=new.season),0)
    into v_count;

    if v_count>=8 and not exists(
      select 1 from public.record_occurrences where record_code='player_of_year_awards'
        and player_id=new.player_id and coalesce(value,0)>=v_count
    ) then
      insert into public.record_occurrences(record_code,player_id,player_name,country,season,achieved_on,value,label,source_type,source_label,source_url,metadata)
      values('player_of_year_awards',new.player_id,new.player_name,new.country,new.season,v_date,v_count,
        v_count||' awards joueur de l’année','career','Court Boss · awards v1','',jsonb_build_object('season',new.season));
    end if;
  end if;
  return new;
end;
$function$;

drop trigger if exists trg_cb_award_world_news on public.court_boss_player_awards;
create trigger trg_cb_award_world_news
after insert on public.court_boss_player_awards
for each row execute function public.court_boss_award_world_news_trigger();

create or replace function public.court_boss_publish_daily_legacy_rank_moves(p_date date)
returns jsonb
language plpgsql
security invoker
set search_path to ''
as $function$
declare
  r record; v_published int:=0; v_threshold int; v_displaced text; v_body text;
begin
  if p_date<=date '2025-12-01' then return jsonb_build_object('date',p_date,'published',0); end if;
  for r in
    with active as (
      select distinct player_id from public.court_boss_match_stat_lines where match_date=p_date
    ),
    before_rank as (
      select l.* from public.court_boss_legacy_leaderboard(p_date-1) l join active a on a.player_id=l.player_id
    ),
    after_rank as (
      select l.* from public.court_boss_legacy_leaderboard(p_date) l join active a on a.player_id=l.player_id
    )
    select a.player_id,a.player_name,a.all_time_rank after_rank,a.legacy_score,b.all_time_rank before_rank
    from after_rank a left join before_rank b on b.player_id=a.player_id
    where (a.all_time_rank=1 and coalesce(b.all_time_rank,999999)>1)
      or (a.all_time_rank<=3 and coalesce(b.all_time_rank,999999)>3)
      or (a.all_time_rank<=5 and coalesce(b.all_time_rank,999999)>5)
      or (a.all_time_rank<=10 and coalesce(b.all_time_rank,999999)>10)
      or (a.all_time_rank<=20 and coalesce(b.all_time_rank,999999)>20)
    order by a.all_time_rank
  loop
    v_threshold:=case
      when r.after_rank=1 and coalesce(r.before_rank,999999)>1 then 1
      when r.after_rank<=3 and coalesce(r.before_rank,999999)>3 then 3
      when r.after_rank<=5 and coalesce(r.before_rank,999999)>5 then 5
      when r.after_rank<=10 and coalesce(r.before_rank,999999)>10 then 10
      else 20 end;

    select player_name into v_displaced
    from public.court_boss_legacy_leaderboard(p_date-1)
    where all_time_rank=r.after_rank and player_id<>r.player_id
    order by legacy_score desc limit 1;

    v_body:=case when v_threshold=1
      then r.player_name||' prend la tête du classement Legacy all-time'
      else r.player_name||' entre dans le Top '||v_threshold||' du classement Legacy all-time' end
      ||case when v_displaced is not null then ' en dépassant '||v_displaced else '' end
      ||' grâce à sa progression sur le circuit.';

    if public.court_boss_publish_world_story(
      'legacy_top_'||v_threshold||':'||r.player_id,p_date,r.player_id,'legacy_rank',v_body,
      jsonb_build_object('before_rank',r.before_rank,'after_rank',r.after_rank,'threshold',v_threshold,
        'displaced_player',v_displaced,'legacy_score',r.legacy_score)
    ) then v_published:=v_published+1; end if;
  end loop;
  return jsonb_build_object('date',p_date,'published',v_published,'model','CB-LEGACY-NEWS-v1');
end;
$function$;

create or replace function public.advance_career_day_v26(
  p_today_plan jsonb default '{}'::jsonb,
  p_difficulty text default 'normal'::text,
  p_expected_from_date date default null::date
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_current public.career_state%rowtype;
  v_existing jsonb;
  v_result jsonb;
  v_result_date date;
  v_story_date date;
  v_legacy_news jsonb:=jsonb_build_object('published',0);
  v_week int;
begin
  perform pg_advisory_xact_lock(2200261201);
  select * into v_current from public.career_state where id='demo' for update;
  if not found then return jsonb_build_object('ok',false,'reason','career_missing','model','CB-DAILY-CLOCK-v26'); end if;

  if p_expected_from_date is not null then
    select cel.payload->'result' into v_existing
    from public.career_event_log cel
    where cel.event_type='daily_tick_commit_v25'
      and coalesce(cel.payload->>'from_date','')=p_expected_from_date::text
    order by cel.id desc limit 1;
    if v_existing is not null then
      return v_existing||jsonb_build_object('ok',true,'already_applied',true,'idempotent_replay',true,
        'expected_from_date',p_expected_from_date,'model','CB-DAILY-CLOCK-v26');
    end if;
    if coalesce(v_current.career_date,date '2025-12-01')<>p_expected_from_date then
      return jsonb_build_object('ok',false,'reason','stale_day_request','retryable',false,
        'expected_from_date',p_expected_from_date,'current_date',v_current.career_date,'model','CB-DAILY-CLOCK-v26');
    end if;
  end if;

  v_result:=public.advance_career_day_v22(coalesce(p_today_plan,'{}'::jsonb),coalesce(p_difficulty,'normal'));

  if coalesce((v_result->>'ok')::boolean,false)=true and nullif(v_result->>'date','') is not null then
    v_result_date:=(v_result->>'date')::date;
    v_week:=coalesce((v_result->>'week')::int,1);
    v_story_date:=coalesce(p_expected_from_date,nullif(v_result->>'from_date','')::date,v_result_date-1);
    v_legacy_news:=public.court_boss_publish_daily_legacy_rank_moves(v_story_date);
    v_result:=v_result||jsonb_build_object('legacy_news',v_legacy_news);

    insert into public.career_event_log(event_date,week,system,event_type,entity_type,entity_id,summary,payload)
    values(v_result_date,v_week,'clock','daily_tick_commit_v25','career',null,
      'Commit journée idempotent '||coalesce(p_expected_from_date::text,(v_result->>'from_date'),'')||' → '||v_result_date::text,
      jsonb_build_object('from_date',coalesce(p_expected_from_date::text,v_result->>'from_date'),
        'to_date',v_result_date,'result',v_result));
  end if;

  return coalesce(v_result,'{}'::jsonb)||jsonb_build_object(
    'expected_from_date',p_expected_from_date,'model','CB-DAILY-CLOCK-v26'
  );
end;
$function$;

revoke all on function public.court_boss_legacy_leaderboard(date) from public,anon,authenticated;
grant execute on function public.court_boss_legacy_leaderboard(date) to service_role;
revoke all on function public.court_boss_all_time_snapshot(bigint,date) from public,anon,authenticated;
grant execute on function public.court_boss_all_time_snapshot(bigint,date) to service_role;
revoke all on function public.court_boss_publish_world_story(text,date,bigint,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.court_boss_publish_world_story(text,date,bigint,text,text,jsonb) to service_role;
revoke all on function public.court_boss_publish_record_occurrence_news(bigint) from public,anon,authenticated;
grant execute on function public.court_boss_publish_record_occurrence_news(bigint) to service_role;
revoke all on function public.court_boss_publish_legacy_rank_story(bigint,date,text) from public,anon,authenticated;
grant execute on function public.court_boss_publish_legacy_rank_story(bigint,date,text) to service_role;
revoke all on function public.court_boss_publish_title_legacy_story(bigint,date,text,text) from public,anon,authenticated;
grant execute on function public.court_boss_publish_title_legacy_story(bigint,date,text,text) to service_role;
revoke all on function public.court_boss_publish_daily_legacy_rank_moves(date) from public,anon,authenticated;
grant execute on function public.court_boss_publish_daily_legacy_rank_moves(date) to service_role;
revoke all on function public.court_boss_record_occurrence_news_trigger() from public,anon,authenticated;
revoke all on function public.court_boss_award_world_news_trigger() from public,anon,authenticated;
revoke all on function public.court_boss_record_title_trigger() from public,anon,authenticated;
